In [4]:
import io
from google.cloud import vision
from google.cloud.vision import types
import pandas as pd

In [5]:
def get_text(image_file, symbol_search=None):
    """Get text from images"""
    client = vision.ImageAnnotatorClient()

    bounds = []

    with io.open(image_file, 'rb') as image_file:
        content = image_file.read()

    image = types.Image(content=content)

    response = client.document_text_detection(image=image)
    document = response.full_text_annotation

    df = pd.DataFrame()

    # Collect specified feature bounds by enumerating all document features
    for n_page, page in enumerate(document.pages):
        for n_block, block in enumerate(page.blocks):
            for n_paragraph, paragraph in enumerate(block.paragraphs):
                for n_word, word in enumerate(paragraph.words):

                    symbol_search_find = False
                    n_symbol_search_find = None

                    for n_symbol, symbol in enumerate(word.symbols):
                        if symbol.text == symbol_search:
                            
                            print('find simbol')
                            symbol_search_find = True
                            n_symbol_search_find = n_symbol

                    df_temp = pd.DataFrame({
                                            'n_page': n_page,
                                            'page_height': [page.height],
                                            'page_width': [page.width],
                                            'n_block': [n_block],
                                            'block_vert': [[(vertex.x, vertex.y) for vertex in block.bounding_box.vertices]],
                                            'block_confidence': block.confidence,
                                            'n_paragraph': n_paragraph,
                                            'paragraph_vert': [[(vertex.x, vertex.y) for vertex in paragraph.bounding_box.vertices]],
                                            'paragraph_confidence': paragraph.confidence,
                                            'n_word': n_word,
                                            'word_vert': [[(vertex.x, vertex.y) for vertex in word.bounding_box.vertices]],
                                            "word_confidence": word.confidence,
                                            "text": [[symbol.text for symbol in word.symbols]],
                                            "symbol_search_pos": symbol_search_find,
                                            "n_symbol_search_find": n_symbol_search_find,
                                            })

                    df = df.append(df_temp, ignore_index=True)


     
    return df

# Get Text From Images

In [6]:
import os
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "C:/Users/scors/Credentials/Raxar-12e4ceccdc19.json"

In [14]:
folder = '../data/raw/'

In [15]:
files = [ str(i) + '.jpg' for i in range(1, 21)]

In [19]:
symbol_search = '$'

In [20]:
df = pd.DataFrame()

for file in files:
    print(file)
    df_temp = get_text(folder + file, symbol_search)
    df_temp['file'] = file
    df = df.append(df_temp)
    
df = df.reset_index()
df = df.set_index(['file', 'index'])

1.jpg
find simbol
find simbol
2.jpg
find simbol
3.jpg
find simbol
find simbol
4.jpg
find simbol
find simbol
5.jpg
6.jpg
find simbol
find simbol
7.jpg
find simbol
find simbol
8.jpg
find simbol
find simbol
9.jpg
find simbol
find simbol
10.jpg
find simbol
find simbol
11.jpg
find simbol
12.jpg
find simbol
13.jpg
find simbol
find simbol
14.jpg
find simbol
15.jpg
16.jpg
find simbol
17.jpg
find simbol
find simbol
18.jpg
19.jpg
find simbol
20.jpg
find simbol

In [25]:
df.shape

(540, 16)

# Create Target

In [28]:
df['y'] = 0

In [29]:
df.xs('1.jpg', level='file')

,n_page,page_height,page_width,n_block,block_vert,block_confidence,n_paragraph,paragraph_vert,paragraph_confidence,n_word,word_vert,word_confidence,text,symbol_search_pos,n_symbol_search_find,y
index,,,,,,,,,,,,,,,,
0,0,719,1280,0,"[(307, 251), (474, 255), (473, 320), (306, 316)]",0.97,0,"[(307, 251), (474, 255), (473, 320), (306, 316)]",0.97,0,"[(307, 251), (354, 253), (353, 270), (306, 268)]",0.98,"[W, W, W]",False,None,0
1,0,719,1280,0,"[(307, 251), (474, 255), (473, 320), (306, 316)]",0.97,0,"[(307, 251), (474, 255), (473, 320), (306, 316)]",0.97,1,"[(312, 272), (469, 274), (469, 296), (312, 294)]",0.98,"[p, r, e, c, i, o, s, c, u, i, d, a, d, o, s]",False,None,0
2,0,719,1280,0,"[(307, 251), (474, 255), (473, 320), (306, 316)]",0.97,0,"[(307, 251), (474, 255), (473, 320), (306, 316)]",0.97,2,"[(472, 275), (474, 275), (474, 296), (472, 296)]",0.90,[.],False,None,0
3,0,719,1280,0,"[(307, 251), (474, 255), (473, 320), (306, 316)]",0.97,0,"[(307, 251), (474, 255), (473, 320), (306, 316)]",0.97,3,"[(315, 294), (374, 295), (374, 317), (315, 316)]",0.95,"[g, o, b, ., a, r]",False,None,0
4,0,719,1280,1,"[(573, 285), (608, 286), (608, 297), (573, 296)]",0.44,0,"[(573, 285), (608, 286), (608, 297), (573, 296)]",0.44,0,"[(573, 285), (608, 286), (608, 297), (573, 296)]",0.44,"[A, n, t]",False,None,0
5,0,719,1280,2,"[(645, 290), (767, 291), (767, 310), (645, 309)]",0.99,0,"[(645, 290), (767, 291), (767, 310), (645, 309)]",0.99,0,"[(645, 290), (720, 291), (720, 310), (645, 309)]",0.99,"[A, r, g, e, n, t, i, n, a]",False,None,0
6,0,719,1280,2,"[(645, 290), (767, 291), (767, 310), (645, 309)]",0.99,0,"[(645, 290), (767, 291), (767, 310), (645, 309)]",0.99,1,"[(725, 291), (767, 291), (767, 310), (725, 310)]",0.99,"[u, n, i, d, a]",False,None,0
7,0,719,1280,3,"[(77, 231), (946, 246), (943, 396), (74, 381)]",0.95,0,"[(77, 233), (259, 234), (259, 312), (77, 311)]",0.98,0,"[(77, 233), (219, 234), (219, 280), (77, 279)]",0.98,"[p, r, e, c, i, o, s]",False,None,0
8,0,719,1280,3,"[(77, 231), (946, 246), (943, 396), (74, 381)]",0.95,0,"[(77, 233), (259, 234), (259, 312), (77, 311)]",0.98,1,"[(82, 272), (259, 272), (259, 311), (82, 311)]",0.98,"[c, u, i, d, a, d, o, s]",False,None,0
9,0,719,1280,3,"[(77, 231), (946, 246), (943, 396), (74, 381)]",0.95,1,"[(174, 329), (944, 352), (942, 396), (173, 373)]",0.94,0,"[(174, 329), (341, 334), (340, 378), (173, 373)]",0.99,"[g, a, s, e, o, s, a]",False,None,0
10,0,719,1280,3,"[(77, 231), (946, 246), (943, 396), (74, 381)]",0.95,1,"[(174, 329), (944, 352), (942, 396), (173, 373)]",0.94,1,"[(356, 335), (471, 338), (470, 381), (355, 378)]",0.99,"[C, O, C, A]",False,None,0
11,0,719,1280,3,"[(77, 231), (946, 246), (943, 396), (74, 381)]",0.95,1,"[(174, 329), (944, 352), (942, 396), (173, 373)]",0.94,2,"[(486, 339), (593, 342), (592, 385), (485, 382)]",1.00,"[C, O, L, A]",False,None,0
12,0,719,1280,3,"[(77, 231), (946, 246), (943, 396), (74, 381)]",0.95,1,"[(174, 329), (944, 352), (942, 396), (173, 373)]",0.94,3,"[(618, 343), (673, 345), (672, 388), (617, 386)]",0.98,"[1, ., 2, 5]",False,None,0
13,0,719,1280,3,"[(77, 231), (946, 246), (943, 396), (74, 381)]",0.95,1,"[(174, 329), (944, 352), (942, 396), (173, 373)]",0.94,4,"[(686, 345), (698, 345), (697, 388), (685, 388)]",0.99,[-],False,None,0
14,0,719,1280,3,"[(77, 231), (946, 246), (943, 396), (74, 381)]",0.95,1,"[(174, 329), (944, 352), (942, 396), (173, 373)]",0.94,5,"[(710, 346), (724, 346), (723, 389), (709, 389)]",0.72,"[I, t]",False,None,0
15,0,719,1280,3,"[(77, 231), (946, 246), (943, 396), (74, 381)]",0.95,1,"[(174, 329), (944, 352), (942, 396), (173, 373)]",0.94,6,"[(747, 346), (834, 349), (833, 393), (746, 390)]",0.94,"[B, O, T]",False,None,0
16,0,719,1280,3,"[(77, 231), (946, 246), (943, 396), (74, 381)]",0.95,1,"[(174, 329), (944, 352), (942, 396), (173, 373)]",0.94,7,"[(843, 349), (916, 351), (915, 395), (842, 393)]",0.99,"[1, ., 2, 5]",False,None,0
17,0,719,1280,3,"[(77, 231), (946, 246), (943, 396), (74, 381)]",0.95,1,"[(174, 329), (944, 352), (942, 396), (173, 373)]",0.94,8,"[(935, 352), (944, 352), (943, 395), (934, 395)]",0.21,[1],False,None,0
18,0,719,1280,4,"[(177, 421), (301, 425), (301, 440), (177, 436)]",0.96,0,"[(177, 421), (301, 425), (301, 440), (177, 436)]",0.96,0,"[(177, 421), (220, 422), (220, 437), (177, 436)]",0.99,"[O, R, I, G, E, N]",False,None,0
19,0,719,1280,4,"[(177, 421), (301, 425), (301, 440), (177, 436)]",0.96,0,"[(177, 421), (301, 425), (301, 440), (177, 436)]",0.96,1,"[(226, 423), (227, 423), (227, 437), (226, 437)]",0.85,[:],False,None,0
20,0,719,1280,4,"[(177, 421), (301, 425), (301, 440), (177, 436)]",0.96,0,"[(177, 421), (301, 425), (301, 440), (177, 436)]",0.96,2,"[(231, 423), (301, 425), (301, 440), (231, 438)]",0.95,"[A, R, G, E, N, T, I, N, A]",False,None,0
21,0,719,1280,5,"[(433, 437), (752, 423), (756, 526), (437, 540)]",0.98,0,"[(433, 437), (752, 423), (756, 526), (437, 540)]",0.98,0,"[(433, 437), (458, 436), (462, 539), (437, 540)]",0.98,[$],True,0,0
22,0,719,1280,5,"[(433, 437), (752, 423), (756, 526), (437, 540)]",0.98,0,"[(433, 437), (752, 423), (756, 526), (437, 540)]",0.98,1,"[(505, 434), (752, 424), (756, 526), (509, 537)]",0.98,"[8, 7, ., 5, 0]",False,None,0
23,0,719,1280,6,"[(-6, 494), (48, 493), (49, 548), (-5, 549)]",0.23,0,"[(-6, 494), (48, 493), (49, 548), (-5, 549)]",0.23,0,"[(-6, 494), (48, 493), (49, 548), (-5, 549)]",0.23,[o],False,None,0
24,0,719,1280,7,"[(29, 502), (121, 504), (118, 632), (26, 630)]",0.97,0,"[(29, 502), (121, 504), (118, 632), (26, 630)]",0.97,0,"[(29, 502), (121, 504), (118, 632), (26, 630)]",0.97,"[o, l, u]",False,None,0
25,0,719,1280,8,"[(198, 550), (552, 567), (550, 596), (197, 579)]",0.98,0,"[(198, 550), (552, 567), (550, 596), (197, 579)]",0.98,0,"[(198, 550), (262, 553), (261, 581), (197, 578)]",0.97,"[S, U, M, Á]",False,None,0
26,0,719,1280,8,"[(198, 550), (552, 567), (550, 596), (197, 579)]",0.98,0,"[(198, 550), (552, 567), (550, 596), (197, 579)]",0.98,1,"[(279, 554), (310, 555), (309, 583), (278, 582)]",0.95,"[6, 1, 3]",False,None,0
27,0,719,1280,8,"[(198, 550), (552, 567), (550, 596), (197, 579)]",0.98,0,"[(198, 550), (552, 567), (550, 596), (197, 579)]",0.98,2,"[(319, 556), (408, 560), (407, 588), (318, 584)]",0.99,"[P, U, N, T, O, S]",False,None,0
28,0,719,1280,8,"[(198, 550), (552, 567), (550, 596), (197, 579)]",0.98,0,"[(198, 550), (552, 567), (550, 596), (197, 579)]",0.98,3,"[(418, 561), (496, 565), (495, 593), (417, 589)]",0.99,"[J, U, M, B, O]",False,None,0
29,0,719,1280,8,"[(198, 550), (552, 567), (550, 596), (197, 579)]",0.98,0,"[(198, 550), (552, 567), (550, 596), (197, 579)]",0.98,4,"[(507, 565), (552, 567), (551, 594), (506, 592)]",0.98,"[M, Á, S]",False,None,0
30,0,719,1280,9,"[(528, 552), (650, 560), (649, 575), (527, 567)]",0.93,0,"[(528, 552), (650, 560), (649, 575), (527, 567)]",0.93,0,"[(528, 552), (577, 555), (576, 570), (527, 567)]",0.99,"[P, R, E, C, I, O]",False,None,0
31,0,719,1280,9,"[(528, 552), (650, 560), (649, 575), (527, 567)]",0.93,0,"[(528, 552), (650, 560), (649, 575), (527, 567)]",0.93,1,"[(583, 556), (604, 557), (603, 571), (582, 570)]",0.93,"[X, L]",False,None,0
32,0,719,1280,9,"[(528, 552), (650, 560), (649, 575), (527, 567)]",0.93,0,"[(528, 552), (650, 560), (649, 575), (527, 567)]",0.93,2,"[(606, 558), (610, 558), (609, 572), (605, 572)]",0.77,[$],True,0,0
33,0,719,1280,9,"[(528, 552), (650, 560), (649, 575), (527, 567)]",0.93,0,"[(528, 552), (650, 560), (649, 575), (527, 567)]",0.93,3,"[(614, 558), (650, 560), (649, 575), (613, 573)]",0.90,"[7, 0, ., 0, 0]",False,None,0
34,0,719,1280,10,"[(940, 584), (1054, 591), (1053, 606), (939, 5...",0.91,0,"[(940, 584), (1054, 591), (1053, 606), (939, 5...",0.91,0,"[(940, 584), (1054, 591), (1053, 606), (939, 5...",0.91,"[7, 7, 9, 0, 8, 9, 5, 0, 1, 2, 2, 6, 6]",False,None,0

In [30]:
df.loc[('1.jpg', 22), 'y'] = 1

In [31]:
df.xs('2.jpg', level='file')

,n_page,page_height,page_width,n_block,block_vert,block_confidence,n_paragraph,paragraph_vert,paragraph_confidence,n_word,word_vert,word_confidence,text,symbol_search_pos,n_symbol_search_find,y
index,,,,,,,,,,,,,,,,
0,0,581,1032,0,"[(143, 124), (772, 121), (772, 238), (143, 241)]",0.91,0,"[(144, 124), (287, 125), (287, 189), (144, 188)]",0.96,0,"[(144, 124), (258, 125), (258, 164), (144, 163)]",0.99,"[p, r, e, c, i, o, s]",False,None,0
1,0,581,1032,0,"[(143, 124), (772, 121), (772, 238), (143, 241)]",0.91,0,"[(144, 124), (287, 125), (287, 189), (144, 188)]",0.96,1,"[(147, 158), (287, 158), (287, 188), (147, 188)]",0.94,"[c, u, i, d, a, d, o, s]",False,None,0
2,0,581,1032,0,"[(143, 124), (772, 121), (772, 238), (143, 241)]",0.91,1,"[(215, 206), (772, 198), (772, 233), (215, 241)]",0.88,0,"[(215, 207), (345, 205), (345, 239), (215, 241)]",0.99,"[g, a, s, e, o, s, a]",False,None,0
3,0,581,1032,0,"[(143, 124), (772, 121), (772, 238), (143, 241)]",0.91,1,"[(215, 206), (772, 198), (772, 233), (215, 241)]",0.88,1,"[(359, 205), (443, 204), (443, 238), (359, 239)]",0.99,"[C, O, C, A]",False,None,0
4,0,581,1032,0,"[(143, 124), (772, 121), (772, 238), (143, 241)]",0.91,1,"[(215, 206), (772, 198), (772, 233), (215, 241)]",0.88,2,"[(456, 204), (531, 203), (531, 236), (456, 237)]",1.00,"[C, O, L, A]",False,None,0
5,0,581,1032,0,"[(143, 124), (772, 121), (772, 238), (143, 241)]",0.91,1,"[(215, 206), (772, 198), (772, 233), (215, 241)]",0.88,3,"[(545, 202), (628, 201), (628, 235), (545, 236)]",0.76,"[1, ., 2, 5, -, 1, 7]",False,None,0
6,0,581,1032,0,"[(143, 124), (772, 121), (772, 238), (143, 241)]",0.91,1,"[(215, 206), (772, 198), (772, 233), (215, 241)]",0.88,4,"[(640, 201), (695, 200), (695, 234), (640, 235)]",0.73,"[B, O, T]",False,None,0
7,0,581,1032,0,"[(143, 124), (772, 121), (772, 238), (143, 241)]",0.91,1,"[(215, 206), (772, 198), (772, 233), (215, 241)]",0.88,5,"[(706, 200), (753, 199), (753, 233), (706, 234)]",0.97,"[1, ., 2, 5]",False,None,0
8,0,581,1032,0,"[(143, 124), (772, 121), (772, 238), (143, 241)]",0.91,1,"[(215, 206), (772, 198), (772, 233), (215, 241)]",0.88,6,"[(766, 200), (772, 200), (772, 233), (766, 233)]",0.15,[/],False,None,0
9,0,581,1032,1,"[(325, 137), (450, 141), (448, 194), (323, 190)]",0.94,0,"[(325, 137), (450, 141), (448, 194), (323, 190)]",0.94,0,"[(325, 137), (362, 139), (361, 154), (324, 152)]",0.97,"[w, w, w]",False,None,0
10,0,581,1032,1,"[(325, 137), (450, 141), (448, 194), (323, 190)]",0.94,0,"[(325, 137), (450, 141), (448, 194), (323, 190)]",0.94,1,"[(331, 154), (449, 154), (449, 173), (331, 173)]",0.96,"[p, r, e, c, i, o, s, c, u, i, d, a, d, o, s]",False,None,0
11,0,581,1032,1,"[(325, 137), (450, 141), (448, 194), (323, 190)]",0.94,0,"[(325, 137), (450, 141), (448, 194), (323, 190)]",0.94,2,"[(331, 172), (377, 173), (377, 191), (331, 190)]",0.87,"[g, o, b, ., a, r]",False,None,0
12,0,581,1032,2,"[(529, 157), (660, 160), (660, 177), (529, 174)]",0.59,0,"[(529, 157), (660, 160), (660, 177), (529, 174)]",0.59,0,"[(529, 158), (539, 158), (539, 174), (529, 174)]",0.24,"[A, r, a]",False,None,0
13,0,581,1032,2,"[(529, 157), (660, 160), (660, 177), (529, 174)]",0.59,0,"[(529, 157), (660, 160), (660, 177), (529, 174)]",0.59,1,"[(577, 158), (628, 159), (628, 176), (577, 175)]",0.53,"[A, r, g, e, n, t, i, n, a]",False,None,0
14,0,581,1032,2,"[(529, 157), (660, 160), (660, 177), (529, 174)]",0.59,0,"[(529, 157), (660, 160), (660, 177), (529, 174)]",0.59,2,"[(632, 160), (660, 161), (660, 177), (632, 176)]",0.91,"[u, n, i, d, a]",False,None,0
15,0,581,1032,3,"[(213, 278), (312, 277), (312, 287), (213, 288)]",0.95,0,"[(213, 278), (312, 277), (312, 287), (213, 288)]",0.95,0,"[(213, 278), (247, 278), (247, 288), (213, 288)]",0.99,"[O, R, I, G, E, N]",False,None,0
16,0,581,1032,3,"[(213, 278), (312, 277), (312, 287), (213, 288)]",0.95,0,"[(213, 278), (312, 277), (312, 287), (213, 288)]",0.95,1,"[(252, 278), (253, 278), (253, 288), (252, 288)]",0.87,[:],False,None,0
17,0,581,1032,3,"[(213, 278), (312, 277), (312, 287), (213, 288)]",0.95,0,"[(213, 278), (312, 277), (312, 287), (213, 288)]",0.95,2,"[(256, 278), (312, 278), (312, 288), (256, 288)]",0.94,"[A, R, G, E, N, T, I, N, A]",False,None,0
18,0,581,1032,4,"[(411, 286), (638, 260), (646, 338), (420, 363)]",0.98,0,"[(411, 286), (638, 260), (646, 338), (420, 363)]",0.98,0,"[(411, 286), (429, 284), (438, 360), (420, 363)]",0.99,[$],True,0,0
19,0,581,1032,4,"[(411, 286), (638, 260), (646, 338), (420, 363)]",0.98,0,"[(411, 286), (638, 260), (646, 338), (420, 363)]",0.98,1,"[(463, 280), (638, 260), (647, 338), (472, 357)]",0.98,"[8, 7, ., 5, 0]",False,None,0
20,0,581,1032,5,"[(222, 370), (568, 362), (569, 398), (223, 406)]",0.96,0,"[(222, 370), (568, 362), (569, 398), (223, 406)]",0.96,0,"[(480, 364), (516, 364), (516, 376), (480, 376)]",0.99,"[P, R, E, C, I, O]",False,None,0
21,0,581,1032,5,"[(222, 370), (568, 362), (569, 398), (223, 406)]",0.96,0,"[(222, 370), (568, 362), (569, 398), (223, 406)]",0.96,1,"[(520, 364), (533, 364), (533, 376), (520, 376)]",0.96,"[X, L]",False,None,0
22,0,581,1032,5,"[(222, 370), (568, 362), (569, 398), (223, 406)]",0.96,0,"[(222, 370), (568, 362), (569, 398), (223, 406)]",0.96,2,"[(537, 364), (568, 364), (568, 376), (537, 376)]",0.88,"[5, 7, 0, ,, 0, 0]",False,None,0
23,0,581,1032,5,"[(222, 370), (568, 362), (569, 398), (223, 406)]",0.96,0,"[(222, 370), (568, 362), (569, 398), (223, 406)]",0.96,3,"[(222, 385), (274, 383), (275, 404), (223, 406)]",0.98,"[S, U, M, Á]",False,None,0
24,0,581,1032,5,"[(222, 370), (568, 362), (569, 398), (223, 406)]",0.96,0,"[(222, 370), (568, 362), (569, 398), (223, 406)]",0.96,4,"[(287, 383), (313, 382), (314, 403), (288, 404)]",0.97,"[6, 1, 3]",False,None,0
25,0,581,1032,5,"[(222, 370), (568, 362), (569, 398), (223, 406)]",0.96,0,"[(222, 370), (568, 362), (569, 398), (223, 406)]",0.96,5,"[(321, 382), (389, 380), (390, 401), (322, 403)]",0.99,"[P, U, N, T, O, S]",False,None,0
26,0,581,1032,5,"[(222, 370), (568, 362), (569, 398), (223, 406)]",0.96,0,"[(222, 370), (568, 362), (569, 398), (223, 406)]",0.96,6,"[(396, 380), (456, 378), (457, 398), (397, 400)]",0.99,"[J, U, M, B, O]",False,None,0
27,0,581,1032,5,"[(222, 370), (568, 362), (569, 398), (223, 406)]",0.96,0,"[(222, 370), (568, 362), (569, 398), (223, 406)]",0.96,7,"[(463, 378), (497, 377), (498, 397), (464, 398)]",0.97,"[M, Á, S]",False,None,0
28,0,581,1032,6,"[(6, 362), (149, 356), (154, 468), (11, 474)]",0.75,0,"[(6, 362), (149, 356), (154, 468), (11, 474)]",0.75,0,"[(6, 362), (149, 356), (154, 468), (11, 474)]",0.75,"[C, o, l, l]",False,None,0

In [32]:
df.loc[('2.jpg', 19), 'y'] = 1

In [33]:
df.xs('3.jpg', level='file')

,n_page,page_height,page_width,n_block,block_vert,block_confidence,n_paragraph,paragraph_vert,paragraph_confidence,n_word,word_vert,word_confidence,text,symbol_search_pos,n_symbol_search_find,y
index,,,,,,,,,,,,,,,,
0,0,581,1032,0,"[(258, 180), (696, 192), (694, 252), (256, 240)]",0.91,0,"[(258, 180), (696, 192), (694, 252), (256, 240)]",0.91,0,"[(258, 180), (376, 183), (375, 212), (257, 209)]",0.97,"[G, a, s, e, o, s, a]",False,None,0
1,0,581,1032,0,"[(258, 180), (696, 192), (694, 252), (256, 240)]",0.91,0,"[(258, 180), (696, 192), (694, 252), (256, 240)]",0.91,1,"[(389, 184), (462, 186), (461, 215), (388, 213)]",0.98,"[C, O, C, A]",False,None,0
2,0,581,1032,0,"[(258, 180), (696, 192), (694, 252), (256, 240)]",0.91,0,"[(258, 180), (696, 192), (694, 252), (256, 240)]",0.91,2,"[(477, 186), (546, 188), (545, 217), (476, 215)]",0.94,"[C, O, L, A]",False,None,0
3,0,581,1032,0,"[(258, 180), (696, 192), (694, 252), (256, 240)]",0.91,0,"[(258, 180), (696, 192), (694, 252), (256, 240)]",0.91,3,"[(571, 189), (622, 190), (621, 219), (570, 218)]",0.99,"[B, O, T]",False,None,0
4,0,581,1032,0,"[(258, 180), (696, 192), (694, 252), (256, 240)]",0.91,0,"[(258, 180), (696, 192), (694, 252), (256, 240)]",0.91,4,"[(634, 191), (665, 192), (664, 220), (633, 219)]",0.98,"[2, ., 2]",False,None,0
5,0,581,1032,0,"[(258, 180), (696, 192), (694, 252), (256, 240)]",0.91,0,"[(258, 180), (696, 192), (694, 252), (256, 240)]",0.91,5,"[(678, 192), (691, 192), (690, 221), (677, 221)]",0.44,"[1, 4]",False,None,0
6,0,581,1032,0,"[(258, 180), (696, 192), (694, 252), (256, 240)]",0.91,0,"[(258, 180), (696, 192), (694, 252), (256, 240)]",0.91,6,"[(694, 193), (696, 193), (695, 221), (693, 221)]",0.84,[.],False,None,0
7,0,581,1032,0,"[(258, 180), (696, 192), (694, 252), (256, 240)]",0.91,0,"[(258, 180), (696, 192), (694, 252), (256, 240)]",0.91,7,"[(257, 213), (422, 217), (421, 244), (256, 240)]",0.88,"[D, e, s, c, a, r, t, a, b, l, e]",False,None,0
8,0,581,1032,1,"[(259, 273), (534, 271), (535, 353), (260, 355)]",0.49,0,"[(259, 273), (534, 271), (535, 353), (260, 355)]",0.49,0,"[(259, 273), (318, 273), (319, 354), (260, 354)]",0.38,"[M, E]",False,None,0
9,0,581,1032,1,"[(259, 273), (534, 271), (535, 353), (260, 355)]",0.49,0,"[(259, 273), (534, 271), (535, 353), (260, 355)]",0.49,1,"[(370, 272), (391, 272), (392, 353), (371, 353)]",0.24,[$],True,0,0
10,0,581,1032,1,"[(259, 273), (534, 271), (535, 353), (260, 355)]",0.49,0,"[(259, 273), (534, 271), (535, 353), (260, 355)]",0.49,2,"[(399, 272), (510, 271), (511, 353), (400, 354)]",0.70,"[1, 5, 2]",False,None,0
11,0,581,1032,1,"[(259, 273), (534, 271), (535, 353), (260, 355)]",0.49,0,"[(259, 273), (534, 271), (535, 353), (260, 355)]",0.49,3,"[(513, 271), (534, 271), (535, 352), (514, 352)]",0.36,[.],False,None,0
12,0,581,1032,2,"[(294, 365), (497, 369), (496, 412), (293, 408)]",0.87,0,"[(294, 365), (497, 369), (497, 389), (294, 385)]",0.84,0,"[(294, 365), (367, 367), (367, 387), (294, 385)]",0.99,"[P, R, E, C, I, O]",False,None,0
13,0,581,1032,2,"[(294, 365), (497, 369), (496, 412), (293, 408)]",0.87,0,"[(294, 365), (497, 369), (497, 389), (294, 385)]",0.84,1,"[(376, 367), (416, 368), (416, 388), (376, 387)]",0.79,"[X, L, I]",False,None,0
14,0,581,1032,2,"[(294, 365), (497, 369), (496, 412), (293, 408)]",0.87,0,"[(294, 365), (497, 369), (497, 389), (294, 385)]",0.84,2,"[(418, 368), (423, 368), (423, 387), (418, 387)]",0.47,[.],False,None,0
15,0,581,1032,2,"[(294, 365), (497, 369), (496, 412), (293, 408)]",0.87,0,"[(294, 365), (497, 369), (497, 389), (294, 385)]",0.84,3,"[(430, 369), (437, 369), (437, 388), (430, 388)]",0.77,[$],True,0,0
16,0,581,1032,2,"[(294, 365), (497, 369), (496, 412), (293, 408)]",0.87,0,"[(294, 365), (497, 369), (497, 389), (294, 385)]",0.84,4,"[(459, 369), (474, 369), (474, 388), (459, 388)]",0.91,"[9, .]",False,None,0
17,0,581,1032,2,"[(294, 365), (497, 369), (496, 412), (293, 408)]",0.87,0,"[(294, 365), (497, 369), (497, 389), (294, 385)]",0.84,5,"[(477, 370), (480, 370), (480, 389), (477, 389)]",0.26,[-],False,None,0
18,0,581,1032,2,"[(294, 365), (497, 369), (496, 412), (293, 408)]",0.87,0,"[(294, 365), (497, 369), (497, 389), (294, 385)]",0.84,6,"[(481, 370), (497, 370), (497, 389), (481, 389)]",0.93,"[1, 9]",False,None,0
19,0,581,1032,2,"[(294, 365), (497, 369), (496, 412), (293, 408)]",0.87,1,"[(328, 390), (487, 393), (487, 412), (328, 409)]",0.90,0,"[(328, 390), (385, 391), (385, 410), (328, 409)]",0.99,"[O, R, I, G, E, N]",False,None,0
20,0,581,1032,2,"[(294, 365), (497, 369), (496, 412), (293, 408)]",0.87,1,"[(328, 390), (487, 393), (487, 412), (328, 409)]",0.90,1,"[(392, 392), (396, 392), (396, 410), (392, 410)]",0.96,[:],False,None,0
21,0,581,1032,2,"[(294, 365), (497, 369), (496, 412), (293, 408)]",0.87,1,"[(328, 390), (487, 393), (487, 412), (328, 409)]",0.90,2,"[(401, 392), (417, 392), (417, 410), (401, 410)]",0.95,"[A, F]",False,None,0
22,0,581,1032,2,"[(294, 365), (497, 369), (496, 412), (293, 408)]",0.87,1,"[(328, 390), (487, 393), (487, 412), (328, 409)]",0.90,3,"[(421, 392), (487, 393), (487, 412), (421, 411)]",0.80,"[G, E, R, I, N, A]",False,None,0
23,0,581,1032,3,"[(609, 351), (775, 355), (773, 422), (607, 418)]",0.84,0,"[(609, 351), (765, 356), (764, 373), (609, 368)]",0.76,0,"[(609, 352), (613, 352), (613, 368), (609, 368)]",0.39,[2],False,None,0
24,0,581,1032,3,"[(609, 351), (775, 355), (773, 422), (607, 418)]",0.84,0,"[(609, 351), (765, 356), (764, 373), (609, 368)]",0.76,1,"[(637, 352), (765, 356), (764, 373), (637, 369)]",0.80,"[7, 9, 0, 8, 9, 5, a, a, 9, 7]",False,None,0
25,0,581,1032,3,"[(609, 351), (775, 355), (773, 422), (607, 418)]",0.84,1,"[(637, 381), (774, 383), (773, 421), (636, 419)]",0.87,0,"[(683, 382), (774, 384), (774, 401), (683, 399)]",0.90,"[1, 2, 1, 1, 0, 1, 0, 1, 0, 0, 9]",False,None,0
26,0,581,1032,3,"[(609, 351), (775, 355), (773, 422), (607, 418)]",0.84,1,"[(637, 381), (774, 383), (773, 421), (636, 419)]",0.87,1,"[(637, 403), (688, 404), (688, 420), (637, 419)]",0.80,"[I, n, g, r, e, s, o]",False,None,0
27,0,581,1032,3,"[(609, 351), (775, 355), (773, 422), (607, 418)]",0.84,1,"[(637, 381), (774, 383), (773, 421), (636, 419)]",0.87,2,"[(689, 405), (692, 405), (692, 420), (689, 420)]",0.97,[:],False,None,0
28,0,581,1032,3,"[(609, 351), (775, 355), (773, 422), (607, 418)]",0.84,1,"[(637, 381), (774, 383), (773, 421), (636, 419)]",0.87,3,"[(697, 404), (772, 405), (772, 421), (697, 420)]",0.87,"[2, 8, /, 0, 7, /, 2, 0, 2, 0]",False,None,0

In [34]:
df.loc[('3.jpg', 10), 'y'] = 1

In [35]:
df.xs('4.jpg', level='file')

,n_page,page_height,page_width,n_block,block_vert,block_confidence,n_paragraph,paragraph_vert,paragraph_confidence,n_word,word_vert,word_confidence,text,symbol_search_pos,n_symbol_search_find,y
index,,,,,,,,,,,,,,,,
0,0,581,1032,0,"[(315, 181), (709, 160), (711, 191), (317, 212)]",0.86,0,"[(315, 181), (709, 160), (711, 191), (317, 212)]",0.86,0,"[(315, 182), (413, 177), (414, 207), (317, 212)]",0.99,"[g, a, s, e, o, s, a]",False,None,0
1,0,581,1032,0,"[(315, 181), (709, 160), (711, 191), (317, 212)]",0.86,0,"[(315, 181), (709, 160), (711, 191), (317, 212)]",0.86,1,"[(423, 176), (489, 172), (491, 202), (425, 206)]",0.99,"[C, O, C, A]",False,None,0
2,0,581,1032,0,"[(315, 181), (709, 160), (711, 191), (317, 212)]",0.86,0,"[(315, 181), (709, 160), (711, 191), (317, 212)]",0.86,2,"[(501, 172), (557, 169), (559, 199), (503, 202)]",0.98,"[C, O, L, A]",False,None,0
3,0,581,1032,0,"[(315, 181), (709, 160), (711, 191), (317, 212)]",0.86,0,"[(315, 181), (709, 160), (711, 191), (317, 212)]",0.86,3,"[(575, 168), (583, 168), (585, 198), (577, 198)]",0.92,[X],False,None,0
4,0,581,1032,0,"[(315, 181), (709, 160), (711, 191), (317, 212)]",0.86,0,"[(315, 181), (709, 160), (711, 191), (317, 212)]",0.86,4,"[(597, 166), (637, 164), (639, 195), (599, 197)]",0.82,"[1, ., 7, 5]",False,None,0
5,0,581,1032,0,"[(315, 181), (709, 160), (711, 191), (317, 212)]",0.86,0,"[(315, 181), (709, 160), (711, 191), (317, 212)]",0.86,5,"[(671, 163), (710, 161), (712, 191), (673, 193)]",0.27,"[p, e, r]",False,None,0
6,0,581,1032,1,"[(605, 266), (630, 266), (630, 285), (605, 285)]",0.95,0,"[(605, 266), (630, 266), (630, 285), (605, 285)]",0.95,0,"[(605, 266), (630, 266), (630, 285), (605, 285)]",0.95,"[., 7, 2]",False,None,0
7,0,581,1032,2,"[(449, 248), (587, 244), (589, 319), (451, 323)]",0.99,0,"[(449, 248), (587, 244), (589, 319), (451, 323)]",0.99,0,"[(449, 248), (587, 244), (589, 319), (451, 323)]",0.99,"[1, 2, 2]",False,None,0
8,0,581,1032,3,"[(414, 287), (426, 286), (427, 313), (415, 314)]",0.99,0,"[(414, 287), (426, 286), (427, 313), (415, 314)]",0.99,0,"[(414, 287), (426, 286), (427, 313), (415, 314)]",0.99,[$],True,0,0
9,0,581,1032,4,"[(362, 337), (510, 331), (511, 364), (363, 371)]",0.80,0,"[(362, 338), (499, 331), (500, 351), (363, 358)]",0.78,0,"[(362, 339), (418, 336), (419, 355), (363, 358)]",0.99,"[P, R, E, C, I, O]",False,None,0
10,0,581,1032,4,"[(362, 337), (510, 331), (511, 364), (363, 371)]",0.80,0,"[(362, 338), (499, 331), (500, 351), (363, 358)]",0.78,1,"[(430, 336), (452, 335), (453, 353), (431, 354)]",0.57,"[X, I]",False,None,0
11,0,581,1032,4,"[(362, 337), (510, 331), (511, 364), (363, 371)]",0.80,0,"[(362, 338), (499, 331), (500, 351), (363, 358)]",0.78,2,"[(459, 334), (464, 334), (465, 352), (460, 352)]",0.62,[$],True,0,0
12,0,581,1032,4,"[(362, 337), (510, 331), (511, 364), (363, 371)]",0.80,0,"[(362, 338), (499, 331), (500, 351), (363, 358)]",0.78,3,"[(470, 333), (499, 332), (500, 351), (471, 352)]",0.61,"[7, 0, ., 1]",False,None,0
13,0,581,1032,4,"[(362, 337), (510, 331), (511, 364), (363, 371)]",0.80,1,"[(391, 353), (511, 349), (512, 365), (392, 369)]",0.82,0,"[(391, 353), (437, 351), (438, 367), (392, 369)]",0.89,"[O, R, I, G, E, N]",False,None,0
14,0,581,1032,4,"[(362, 337), (510, 331), (511, 364), (363, 371)]",0.80,1,"[(391, 353), (511, 349), (512, 365), (392, 369)]",0.82,1,"[(447, 351), (511, 349), (512, 365), (448, 367)]",0.75,"[A, R, G, I, N, T]",False,None,0

In [36]:
df.loc[('4.jpg', 7), 'y'] = 1

In [37]:
df.xs('5.jpg', level='file')

,n_page,page_height,page_width,n_block,block_vert,block_confidence,n_paragraph,paragraph_vert,paragraph_confidence,n_word,word_vert,word_confidence,text,symbol_search_pos,n_symbol_search_find,y
index,,,,,,,,,,,,,,,,
0,0,719,1280,0,"[(790, 707), (855, 681), (863, 700), (798, 726)]",0.78,0,"[(790, 707), (855, 681), (863, 700), (798, 726)]",0.78,0,"[(792, 706), (823, 698), (827, 715), (796, 722)]",0.91,"[O, R]",False,None,0
1,0,719,1280,0,"[(790, 707), (855, 681), (863, 700), (798, 726)]",0.78,0,"[(790, 707), (855, 681), (863, 700), (798, 726)]",0.78,1,"[(826, 699), (854, 683), (861, 696), (834, 712)]",0.69,"[O, R, I]",False,None,0
2,0,719,1280,1,"[(654, 289), (770, 266), (774, 290), (659, 313)]",0.80,0,"[(654, 289), (770, 266), (774, 290), (659, 313)]",0.80,0,"[(654, 289), (721, 276), (725, 299), (658, 312)]",0.74,"[g, o, s, t, o, s, a]",False,None,0
3,0,719,1280,1,"[(654, 289), (770, 266), (774, 290), (659, 313)]",0.80,0,"[(654, 289), (770, 266), (774, 290), (659, 313)]",0.80,1,"[(729, 275), (770, 267), (775, 290), (733, 298)]",0.89,"[C, O, C, A]",False,None,0
4,0,719,1280,2,"[(743, 318), (858, 296), (868, 348), (753, 370)]",0.79,0,"[(743, 318), (858, 296), (868, 348), (753, 370)]",0.79,0,"[(743, 318), (832, 301), (842, 353), (753, 370)]",0.99,"[1, 2, 2]",False,None,0
5,0,719,1280,2,"[(743, 318), (858, 296), (868, 348), (753, 370)]",0.79,0,"[(743, 318), (858, 296), (868, 348), (753, 370)]",0.79,1,"[(851, 298), (858, 297), (868, 349), (861, 350)]",0.21,[-],False,None,0
6,0,719,1280,3,"[(939, 622), (1035, 642), (1031, 660), (935, 6...",0.97,0,"[(939, 622), (1035, 642), (1031, 660), (935, 6...",0.97,0,"[(939, 622), (1035, 642), (1031, 660), (935, 6...",0.97,"[O, R, I, G, I, N, A, L]",False,None,0

In [38]:
df.loc[('5.jpg', 4), 'y'] = 1

In [39]:
df.xs('6.jpg', level='file')

,n_page,page_height,page_width,n_block,block_vert,block_confidence,n_paragraph,paragraph_vert,paragraph_confidence,n_word,word_vert,word_confidence,text,symbol_search_pos,n_symbol_search_find,y
index,,,,,,,,,,,,,,,,
0,0,581,1032,0,"[(446, 102), (674, 97), (674, 111), (446, 116)]",0.68,0,"[(446, 102), (674, 97), (674, 111), (446, 116)]",0.68,0,"[(446, 102), (490, 101), (490, 115), (446, 116)]",0.65,"[L, U, L, A]",False,None,0
1,0,581,1032,0,"[(446, 102), (674, 97), (674, 111), (446, 116)]",0.68,0,"[(446, 102), (674, 97), (674, 111), (446, 116)]",0.68,1,"[(500, 101), (539, 100), (539, 113), (500, 114)]",0.73,"[C, U, L, A]",False,None,0
2,0,581,1032,0,"[(446, 102), (674, 97), (674, 111), (446, 116)]",0.68,0,"[(446, 102), (674, 97), (674, 111), (446, 116)]",0.68,2,"[(551, 100), (577, 99), (577, 112), (551, 113)]",0.73,"[1, ., 2, 5]",False,None,0
3,0,581,1032,0,"[(446, 102), (674, 97), (674, 111), (446, 116)]",0.68,0,"[(446, 102), (674, 97), (674, 111), (446, 116)]",0.68,3,"[(583, 99), (585, 99), (585, 112), (583, 112)]",0.49,[-],False,None,0
4,0,581,1032,0,"[(446, 102), (674, 97), (674, 111), (446, 116)]",0.68,0,"[(446, 102), (674, 97), (674, 111), (446, 116)]",0.68,4,"[(590, 99), (597, 99), (597, 112), (590, 112)]",0.78,"[I, T]",False,None,0
5,0,581,1032,0,"[(446, 102), (674, 97), (674, 111), (446, 116)]",0.68,0,"[(446, 102), (674, 97), (674, 111), (446, 116)]",0.68,5,"[(604, 99), (633, 98), (633, 112), (604, 113)]",0.65,"[B, U, R]",False,None,0
6,0,581,1032,0,"[(446, 102), (674, 97), (674, 111), (446, 116)]",0.68,0,"[(446, 102), (674, 97), (674, 111), (446, 116)]",0.68,6,"[(645, 98), (674, 97), (674, 110), (645, 111)]",0.61,"[1, ., 2, 3]",False,None,0
7,0,581,1032,1,"[(451, 172), (460, 172), (460, 190), (451, 190)]",0.96,0,"[(451, 172), (460, 172), (460, 190), (451, 190)]",0.96,0,"[(451, 172), (460, 172), (460, 190), (451, 190)]",0.96,[$],True,0,0
8,0,581,1032,2,"[(479, 145), (704, 143), (705, 198), (480, 200)]",0.52,0,"[(479, 145), (704, 143), (705, 198), (480, 200)]",0.52,0,"[(479, 145), (548, 144), (549, 199), (480, 200)]",0.99,"[8, 7]",False,None,0
9,0,581,1032,2,"[(479, 145), (704, 143), (705, 198), (480, 200)]",0.52,0,"[(479, 145), (704, 143), (705, 198), (480, 200)]",0.52,1,"[(565, 144), (586, 144), (587, 199), (566, 199)]",0.40,"[3, 0]",False,None,0
10,0,581,1032,2,"[(479, 145), (704, 143), (705, 198), (480, 200)]",0.52,0,"[(479, 145), (704, 143), (705, 198), (480, 200)]",0.52,2,"[(607, 144), (704, 143), (705, 198), (608, 199)]",0.18,"[m, m]",False,None,0
11,0,581,1032,3,"[(402, 206), (508, 204), (508, 229), (402, 231)]",0.91,0,"[(402, 206), (505, 204), (505, 218), (402, 220)]",0.92,0,"[(402, 206), (443, 205), (443, 219), (402, 220)]",0.99,"[P, R, E, C, I, O]",False,None,0
12,0,581,1032,3,"[(402, 206), (508, 204), (508, 229), (402, 231)]",0.91,0,"[(402, 206), (505, 204), (505, 218), (402, 220)]",0.92,1,"[(448, 206), (464, 206), (464, 219), (448, 219)]",0.90,"[X, L]",False,None,0
13,0,581,1032,3,"[(402, 206), (508, 204), (508, 229), (402, 231)]",0.91,0,"[(402, 206), (505, 204), (505, 218), (402, 220)]",0.92,2,"[(469, 205), (472, 205), (472, 218), (469, 218)]",0.72,[$],True,0,0
14,0,581,1032,3,"[(402, 206), (508, 204), (508, 229), (402, 231)]",0.91,0,"[(402, 206), (505, 204), (505, 218), (402, 220)]",0.92,3,"[(477, 205), (505, 205), (505, 218), (477, 218)]",0.90,"[7, 0, ., 0, 0]",False,None,0
15,0,581,1032,3,"[(402, 206), (508, 204), (508, 229), (402, 231)]",0.91,1,"[(419, 218), (508, 216), (508, 229), (419, 231)]",0.89,0,"[(419, 218), (456, 217), (456, 230), (419, 231)]",0.97,"[O, R, I, G, E, N]",False,None,0
16,0,581,1032,3,"[(402, 206), (508, 204), (508, 229), (402, 231)]",0.91,1,"[(419, 218), (508, 216), (508, 229), (419, 231)]",0.89,1,"[(460, 217), (508, 216), (508, 229), (460, 230)]",0.84,"[A, R, G, E, N, T, I, N, A]",False,None,0
17,0,581,1032,4,"[(594, 191), (720, 188), (721, 223), (595, 226)]",0.77,0,"[(594, 191), (720, 189), (720, 203), (594, 205)]",0.85,0,"[(594, 191), (656, 190), (656, 204), (594, 205)]",0.83,"[7, 7, 0, 0, 8, 9, 5]",False,None,0
18,0,581,1032,4,"[(594, 191), (720, 188), (721, 223), (595, 226)]",0.77,0,"[(594, 191), (720, 189), (720, 203), (594, 205)]",0.85,1,"[(662, 190), (720, 189), (720, 203), (662, 204)]",0.87,"[0, 1, 2, 2, 6, 6]",False,None,0
19,0,581,1032,4,"[(594, 191), (720, 188), (721, 223), (595, 226)]",0.77,1,"[(614, 206), (705, 203), (706, 223), (615, 226)]",0.74,0,"[(645, 205), (702, 204), (702, 215), (645, 216)]",0.89,"[1, 2, 1, 1, 0, 1, 0, 1, 2, 1, 9]",False,None,0
20,0,581,1032,4,"[(594, 191), (720, 188), (721, 223), (595, 226)]",0.77,1,"[(614, 206), (705, 203), (706, 223), (615, 226)]",0.74,1,"[(614, 216), (649, 215), (649, 225), (614, 226)]",0.73,"[I, m, p, r, e, s, o]",False,None,0
21,0,581,1032,4,"[(594, 191), (720, 188), (721, 223), (595, 226)]",0.77,1,"[(614, 206), (705, 203), (706, 223), (615, 226)]",0.74,2,"[(655, 215), (705, 213), (705, 223), (655, 225)]",0.58,"[1, 5, /, 0, 1, /, 2, 0, 2, 0]",False,None,0

In [40]:
df.loc[('6.jpg', 8), 'y'] = 1

In [41]:
df.xs('7.jpg', level='file')

,n_page,page_height,page_width,n_block,block_vert,block_confidence,n_paragraph,paragraph_vert,paragraph_confidence,n_word,word_vert,word_confidence,text,symbol_search_pos,n_symbol_search_find,y
index,,,,,,,,,,,,,,,,
0,0,581,1032,0,"[(331, 71), (765, 99), (763, 124), (329, 96)]",0.90,0,"[(331, 71), (765, 99), (763, 124), (329, 96)]",0.90,0,"[(331, 71), (422, 77), (420, 102), (329, 96)]",0.97,"[g, a, s, e, o, s, a]",False,None,0
1,0,581,1032,0,"[(331, 71), (765, 99), (763, 124), (329, 96)]",0.90,0,"[(331, 71), (765, 99), (763, 124), (329, 96)]",0.90,1,"[(435, 78), (501, 82), (499, 106), (433, 102)]",0.99,"[C, O, C, A]",False,None,0
2,0,581,1032,0,"[(331, 71), (765, 99), (763, 124), (329, 96)]",0.90,0,"[(331, 71), (765, 99), (763, 124), (329, 96)]",0.90,2,"[(514, 83), (566, 86), (564, 110), (512, 107)]",0.99,"[C, O, L, A]",False,None,0
3,0,581,1032,0,"[(331, 71), (765, 99), (763, 124), (329, 96)]",0.90,0,"[(331, 71), (765, 99), (763, 124), (329, 96)]",0.90,3,"[(581, 87), (618, 89), (616, 114), (579, 112)]",0.84,"[1, ., 2, 5]",False,None,0
4,0,581,1032,0,"[(331, 71), (765, 99), (763, 124), (329, 96)]",0.90,0,"[(331, 71), (765, 99), (763, 124), (329, 96)]",0.90,4,"[(626, 90), (632, 90), (630, 114), (624, 114)]",0.95,[-],False,None,0
5,0,581,1032,0,"[(331, 71), (765, 99), (763, 124), (329, 96)]",0.90,0,"[(331, 71), (765, 99), (763, 124), (329, 96)]",0.90,5,"[(637, 91), (645, 92), (643, 115), (635, 115)]",0.81,"[I, f]",False,None,0
6,0,581,1032,0,"[(331, 71), (765, 99), (763, 124), (329, 96)]",0.90,0,"[(331, 71), (765, 99), (763, 124), (329, 96)]",0.90,6,"[(653, 92), (701, 95), (699, 119), (651, 116)]",0.93,"[B, O, T]",False,None,0
7,0,581,1032,0,"[(331, 71), (765, 99), (763, 124), (329, 96)]",0.90,0,"[(331, 71), (765, 99), (763, 124), (329, 96)]",0.90,7,"[(707, 95), (765, 99), (763, 124), (705, 120)]",0.74,"[1, ., 2, 5, T]",False,None,0
8,0,581,1032,1,"[(423, 152), (569, 144), (573, 224), (427, 232)]",0.94,0,"[(423, 152), (569, 144), (573, 224), (427, 232)]",0.94,0,"[(423, 152), (444, 151), (448, 230), (427, 231)]",0.91,[$],True,0,0
9,0,581,1032,1,"[(423, 152), (569, 144), (573, 224), (427, 232)]",0.94,0,"[(423, 152), (569, 144), (573, 224), (427, 232)]",0.94,1,"[(470, 150), (569, 145), (573, 223), (474, 229)]",0.95,"[8, 7]",False,None,0
10,0,581,1032,2,"[(594, 177), (622, 178), (621, 197), (593, 196)]",0.96,0,"[(594, 177), (622, 178), (621, 197), (593, 196)]",0.96,0,"[(594, 177), (622, 178), (621, 197), (593, 196)]",0.96,"[., 5, 0]",False,None,0
11,0,581,1032,3,"[(359, 223), (512, 232), (510, 266), (357, 257)]",0.96,0,"[(359, 223), (508, 232), (507, 251), (358, 242)]",0.97,0,"[(359, 223), (415, 226), (414, 245), (358, 242)]",0.99,"[P, R, E, C, I, O]",False,None,0
12,0,581,1032,3,"[(359, 223), (512, 232), (510, 266), (357, 257)]",0.96,0,"[(359, 223), (508, 232), (507, 251), (358, 242)]",0.97,1,"[(424, 228), (450, 230), (449, 248), (423, 246)]",0.96,"[X, L]",False,None,0
13,0,581,1032,3,"[(359, 223), (512, 232), (510, 266), (357, 257)]",0.96,0,"[(359, 223), (508, 232), (507, 251), (358, 242)]",0.97,2,"[(456, 230), (461, 230), (460, 248), (455, 248)]",0.90,[$],True,0,0
14,0,581,1032,3,"[(359, 223), (512, 232), (510, 266), (357, 257)]",0.96,0,"[(359, 223), (508, 232), (507, 251), (358, 242)]",0.97,3,"[(467, 230), (508, 232), (507, 250), (466, 248)]",0.97,"[7, 0, ., 0, 0]",False,None,0
15,0,581,1032,3,"[(359, 223), (512, 232), (510, 266), (357, 257)]",0.96,1,"[(385, 243), (511, 250), (510, 266), (384, 259)]",0.95,0,"[(385, 243), (430, 246), (429, 262), (384, 259)]",0.99,"[O, R, I, G, E, N]",False,None,0
16,0,581,1032,3,"[(359, 223), (512, 232), (510, 266), (357, 257)]",0.96,1,"[(385, 243), (511, 250), (510, 266), (384, 259)]",0.95,1,"[(434, 247), (436, 247), (435, 262), (433, 262)]",0.80,[:],False,None,0
17,0,581,1032,3,"[(359, 223), (512, 232), (510, 266), (357, 257)]",0.96,1,"[(385, 243), (511, 250), (510, 266), (384, 259)]",0.95,2,"[(440, 246), (511, 250), (510, 266), (439, 262)]",0.95,"[A, R, G, E, N, T, I, N, A]",False,None,0
18,0,581,1032,4,"[(630, 223), (797, 231), (794, 282), (628, 274)]",0.96,0,"[(630, 223), (797, 232), (796, 250), (629, 241)]",0.97,0,"[(630, 223), (646, 224), (645, 242), (629, 241)]",0.97,"[7, 7]",False,None,0
19,0,581,1032,4,"[(630, 223), (797, 231), (794, 282), (628, 274)]",0.96,0,"[(630, 223), (797, 232), (796, 250), (629, 241)]",0.97,1,"[(666, 225), (714, 228), (713, 246), (665, 243)]",0.99,"[9, 0, 8, 9, 5]",False,None,0
20,0,581,1032,4,"[(630, 223), (797, 231), (794, 282), (628, 274)]",0.96,0,"[(630, 223), (797, 232), (796, 250), (629, 241)]",0.97,2,"[(723, 229), (771, 232), (770, 249), (722, 246)]",0.96,"[0, 1, 2, 2, 6]",False,None,0
21,0,581,1032,4,"[(630, 223), (797, 231), (794, 282), (628, 274)]",0.96,0,"[(630, 223), (797, 232), (796, 250), (629, 241)]",0.97,3,"[(789, 233), (797, 233), (796, 250), (788, 250)]",0.95,[6],False,None,0
22,0,581,1032,4,"[(630, 223), (797, 231), (794, 282), (628, 274)]",0.96,1,"[(657, 245), (779, 249), (778, 279), (656, 275)]",0.96,0,"[(700, 247), (777, 250), (776, 265), (699, 262)]",0.99,"[1, 2, 1, 1, 0, 1, 0, 1, 2, 1, 9]",False,None,0
23,0,581,1032,4,"[(630, 223), (797, 231), (794, 282), (628, 274)]",0.96,1,"[(657, 245), (779, 249), (778, 279), (656, 275)]",0.96,1,"[(657, 260), (701, 261), (700, 276), (657, 275)]",0.98,"[I, m, p, r, e, s, o]",False,None,0
24,0,581,1032,4,"[(630, 223), (797, 231), (794, 282), (628, 274)]",0.96,1,"[(657, 245), (779, 249), (778, 279), (656, 275)]",0.96,2,"[(704, 262), (706, 262), (706, 276), (704, 276)]",0.40,[:],False,None,0
25,0,581,1032,4,"[(630, 223), (797, 231), (794, 282), (628, 274)]",0.96,1,"[(657, 245), (779, 249), (778, 279), (656, 275)]",0.96,3,"[(712, 262), (778, 264), (777, 279), (712, 277)]",0.97,"[1, 5, /, 0, 7, /, 2, 0, 2, 0]",False,None,0

In [42]:
df.loc[('7.jpg', 9), 'y'] = 1

In [43]:
df.xs('8.jpg', level='file')

,n_page,page_height,page_width,n_block,block_vert,block_confidence,n_paragraph,paragraph_vert,paragraph_confidence,n_word,word_vert,word_confidence,text,symbol_search_pos,n_symbol_search_find,y
index,,,,,,,,,,,,,,,,
0,0,960,1280,0,"[(294, 368), (1042, 334), (1044, 376), (296, 4...",0.93,0,"[(294, 368), (1042, 334), (1044, 376), (296, 4...",0.93,0,"[(294, 368), (441, 361), (443, 403), (296, 410)]",0.99,"[g, a, s, e, o, s, a]",False,None,0
1,0,960,1280,0,"[(294, 368), (1042, 334), (1044, 376), (296, 4...",0.93,0,"[(294, 368), (1042, 334), (1044, 376), (296, 4...",0.93,1,"[(466, 360), (566, 355), (568, 397), (468, 402)]",0.99,"[C, O, C, A]",False,None,0
2,0,960,1280,0,"[(294, 368), (1042, 334), (1044, 376), (296, 4...",0.93,0,"[(294, 368), (1042, 334), (1044, 376), (296, 4...",0.93,2,"[(588, 355), (674, 351), (676, 393), (590, 397)]",0.96,"[C, O, L, A]",False,None,0
3,0,960,1280,0,"[(294, 368), (1042, 334), (1044, 376), (296, 4...",0.93,0,"[(294, 368), (1042, 334), (1044, 376), (296, 4...",0.93,3,"[(701, 350), (797, 346), (799, 387), (703, 391)]",0.97,"[1, ., 2, 5, -, 1]",False,None,0
4,0,960,1280,0,"[(294, 368), (1042, 334), (1044, 376), (296, 4...",0.93,0,"[(294, 368), (1042, 334), (1044, 376), (296, 4...",0.93,4,"[(837, 344), (910, 341), (912, 382), (839, 385)]",0.87,"[B, O, T]",False,None,0
5,0,960,1280,0,"[(294, 368), (1042, 334), (1044, 376), (296, 4...",0.93,0,"[(294, 368), (1042, 334), (1044, 376), (296, 4...",0.93,5,"[(929, 339), (992, 336), (994, 378), (931, 381)]",0.97,"[1, ., 2, 5]",False,None,0
6,0,960,1280,0,"[(294, 368), (1042, 334), (1044, 376), (296, 4...",0.93,0,"[(294, 368), (1042, 334), (1044, 376), (296, 4...",0.93,6,"[(1011, 336), (1036, 335), (1038, 376), (1013,...",0.87,"[I, t]",False,None,0
7,0,960,1280,0,"[(294, 368), (1042, 334), (1044, 376), (296, 4...",0.93,0,"[(294, 368), (1042, 334), (1044, 376), (296, 4...",0.93,7,"[(1034, 335), (1042, 335), (1044, 376), (1036,...",0.21,[.],False,None,0
8,0,960,1280,1,"[(509, 472), (654, 474), (653, 581), (508, 579)]",0.99,0,"[(509, 472), (654, 474), (653, 581), (508, 579)]",0.99,0,"[(509, 472), (539, 472), (538, 579), (508, 579)]",0.99,[$],True,0,0
9,0,960,1280,1,"[(509, 472), (654, 474), (653, 581), (508, 579)]",0.99,0,"[(509, 472), (654, 474), (653, 581), (508, 579)]",0.99,1,"[(543, 472), (654, 473), (653, 580), (542, 579)]",0.99,"[8, 7]",False,None,0
10,0,960,1280,2,"[(653, 490), (709, 487), (711, 525), (655, 528)]",0.82,0,"[(653, 490), (709, 487), (711, 525), (655, 528)]",0.82,0,"[(653, 490), (709, 487), (711, 525), (655, 528)]",0.82,"[., 5, 0]",False,None,0
11,0,960,1280,3,"[(830, 563), (992, 558), (993, 579), (831, 584)]",0.59,0,"[(830, 563), (992, 558), (993, 579), (831, 584)]",0.59,0,"[(830, 563), (924, 560), (925, 581), (831, 584)]",0.59,"[7, 9, 0, 9, 8, 9, 5, 1, 1]",False,None,0
12,0,960,1280,3,"[(830, 563), (992, 558), (993, 579), (831, 584)]",0.59,0,"[(830, 563), (992, 558), (993, 579), (831, 584)]",0.59,1,"[(926, 560), (992, 558), (993, 579), (927, 581)]",0.59,"[3, 1, 2, 2, 0]",False,None,0
13,0,960,1280,4,"[(365, 604), (636, 596), (637, 649), (367, 657)]",0.91,0,"[(365, 604), (636, 596), (637, 625), (366, 633)]",0.89,0,"[(365, 605), (462, 602), (463, 630), (366, 633)]",0.99,"[P, R, E, C, I, O]",False,None,0
14,0,960,1280,4,"[(365, 604), (636, 596), (637, 649), (367, 657)]",0.91,0,"[(365, 604), (636, 596), (637, 625), (366, 633)]",0.89,1,"[(474, 602), (486, 602), (487, 629), (475, 629)]",0.98,[X],False,None,0
15,0,960,1280,4,"[(365, 604), (636, 596), (637, 649), (367, 657)]",0.91,0,"[(365, 604), (636, 596), (637, 625), (366, 633)]",0.89,2,"[(499, 601), (530, 600), (531, 628), (500, 629)]",0.94,"[L, T]",False,None,0
16,0,960,1280,4,"[(365, 604), (636, 596), (637, 649), (367, 657)]",0.91,0,"[(365, 604), (636, 596), (637, 625), (366, 633)]",0.89,3,"[(530, 600), (537, 600), (538, 627), (531, 627)]",0.85,[.],False,None,0
17,0,960,1280,4,"[(365, 604), (636, 596), (637, 649), (367, 657)]",0.91,0,"[(365, 604), (636, 596), (637, 625), (366, 633)]",0.89,4,"[(545, 600), (555, 600), (556, 627), (546, 627)]",0.90,[$],True,0,0
18,0,960,1280,4,"[(365, 604), (636, 596), (637, 649), (367, 657)]",0.91,0,"[(365, 604), (636, 596), (637, 625), (366, 633)]",0.89,5,"[(585, 598), (636, 596), (637, 624), (586, 626)]",0.72,"[0, ., 0, 0]",False,None,0
19,0,960,1280,4,"[(365, 604), (636, 596), (637, 649), (367, 657)]",0.91,1,"[(415, 635), (605, 630), (606, 651), (416, 656)]",0.94,0,"[(415, 635), (491, 633), (492, 653), (416, 655)]",0.99,"[O, R, I, G, E, N]",False,None,0
20,0,960,1280,4,"[(365, 604), (636, 596), (637, 649), (367, 657)]",0.91,1,"[(415, 635), (605, 630), (606, 651), (416, 656)]",0.94,1,"[(498, 633), (503, 633), (504, 653), (499, 653)]",0.97,[:],False,None,0
21,0,960,1280,4,"[(365, 604), (636, 596), (637, 649), (367, 657)]",0.91,1,"[(415, 635), (605, 630), (606, 651), (416, 656)]",0.94,2,"[(508, 632), (563, 630), (564, 651), (509, 653)]",0.95,"[A, F, G, E]",False,None,0
22,0,960,1280,4,"[(365, 604), (636, 596), (637, 649), (367, 657)]",0.91,1,"[(415, 635), (605, 630), (606, 651), (416, 656)]",0.94,3,"[(595, 630), (605, 630), (606, 650), (596, 650)]",0.78,"[I, N]",False,None,0
23,0,960,1280,5,"[(826, 603), (1015, 595), (1017, 639), (828, 6...",0.87,0,"[(826, 603), (1015, 595), (1017, 639), (828, 6...",0.87,0,"[(892, 600), (981, 597), (982, 616), (893, 619)]",0.97,"[1, 2, 1, 1, 0, 1, 0, 1]",False,None,0
24,0,960,1280,5,"[(826, 603), (1015, 595), (1017, 639), (828, 6...",0.87,0,"[(826, 603), (1015, 595), (1017, 639), (828, 6...",0.87,1,"[(989, 597), (992, 597), (993, 615), (990, 615)]",0.29,[:],False,None,0
25,0,960,1280,5,"[(826, 603), (1015, 595), (1017, 639), (828, 6...",0.87,0,"[(826, 603), (1015, 595), (1017, 639), (828, 6...",0.87,2,"[(996, 596), (1015, 595), (1016, 614), (997, 6...",0.80,"[1, 9]",False,None,0
26,0,960,1280,5,"[(826, 603), (1015, 595), (1017, 639), (828, 6...",0.87,0,"[(826, 603), (1015, 595), (1017, 639), (828, 6...",0.87,3,"[(827, 627), (898, 624), (899, 644), (828, 647)]",0.81,"[I, n, g, r, e, s, o]",False,None,0
27,0,960,1280,5,"[(826, 603), (1015, 595), (1017, 639), (828, 6...",0.87,0,"[(826, 603), (1015, 595), (1017, 639), (828, 6...",0.87,4,"[(901, 624), (902, 624), (903, 644), (902, 644)]",0.96,[:],False,None,0
28,0,960,1280,5,"[(826, 603), (1015, 595), (1017, 639), (828, 6...",0.87,0,"[(826, 603), (1015, 595), (1017, 639), (828, 6...",0.87,5,"[(910, 623), (1014, 618), (1015, 639), (911, 6...",0.89,"[2, 3, /, 0, 7, /, 2, 0, 2, 0]",False,None,0

In [44]:
df.loc[('8.jpg', 9), 'y'] = 1

In [45]:
df.xs('9.jpg', level='file')

,n_page,page_height,page_width,n_block,block_vert,block_confidence,n_paragraph,paragraph_vert,paragraph_confidence,n_word,word_vert,word_confidence,text,symbol_search_pos,n_symbol_search_find,y
index,,,,,,,,,,,,,,,,
0,0,581,1032,0,"[(258, 151), (710, 151), (710, 210), (258, 210)]",0.91,0,"[(258, 151), (710, 151), (710, 210), (258, 210)]",0.91,0,"[(259, 151), (383, 151), (383, 179), (259, 179)]",0.92,"[G, a, s, e, o, s, a]",False,None,0
1,0,581,1032,0,"[(258, 151), (710, 151), (710, 210), (258, 210)]",0.91,0,"[(258, 151), (710, 151), (710, 210), (258, 210)]",0.91,1,"[(399, 151), (475, 151), (475, 179), (399, 179)]",0.97,"[C, O, C, A]",False,None,0
2,0,581,1032,0,"[(258, 151), (710, 151), (710, 210), (258, 210)]",0.91,0,"[(258, 151), (710, 151), (710, 210), (258, 210)]",0.91,2,"[(488, 151), (557, 151), (557, 179), (488, 179)]",0.99,"[C, O, L, A]",False,None,0
3,0,581,1032,0,"[(258, 151), (710, 151), (710, 210), (258, 210)]",0.91,0,"[(258, 151), (710, 151), (710, 210), (258, 210)]",0.91,3,"[(580, 151), (632, 151), (632, 179), (580, 179)]",0.99,"[B, O, T]",False,None,0
4,0,581,1032,0,"[(258, 151), (710, 151), (710, 210), (258, 210)]",0.91,0,"[(258, 151), (710, 151), (710, 210), (258, 210)]",0.91,4,"[(642, 151), (679, 151), (679, 179), (642, 179)]",0.97,"[2, ., 2]",False,None,0
5,0,581,1032,0,"[(258, 151), (710, 151), (710, 210), (258, 210)]",0.91,0,"[(258, 151), (710, 151), (710, 210), (258, 210)]",0.91,5,"[(690, 151), (705, 151), (705, 179), (690, 179)]",0.54,"[1, 4]",False,None,0
6,0,581,1032,0,"[(258, 151), (710, 151), (710, 210), (258, 210)]",0.91,0,"[(258, 151), (710, 151), (710, 210), (258, 210)]",0.91,6,"[(708, 151), (710, 151), (710, 179), (708, 179)]",0.44,[.],False,None,0
7,0,581,1032,0,"[(258, 151), (710, 151), (710, 210), (258, 210)]",0.91,0,"[(258, 151), (710, 151), (710, 210), (258, 210)]",0.91,7,"[(258, 183), (443, 183), (443, 210), (258, 210)]",0.93,"[D, e, s, c, a, r, t, a, b, l, e]",False,None,0
8,0,581,1032,1,"[(388, 216), (535, 236), (523, 323), (376, 303)]",0.94,0,"[(388, 216), (535, 236), (523, 323), (376, 303)]",0.94,0,"[(388, 217), (413, 220), (401, 307), (376, 303)]",0.86,[$],True,0,0
9,0,581,1032,1,"[(388, 216), (535, 236), (523, 323), (376, 303)]",0.94,0,"[(388, 216), (535, 236), (523, 323), (376, 303)]",0.94,1,"[(424, 221), (535, 236), (523, 323), (412, 308)]",0.96,"[1, 5, 2]",False,None,0
10,0,581,1032,2,"[(516, 247), (558, 247), (558, 275), (516, 275)]",0.85,0,"[(516, 247), (558, 247), (558, 275), (516, 275)]",0.85,0,"[(516, 247), (558, 247), (558, 275), (516, 275)]",0.85,"[1, ., 8, 8]",False,None,0
11,0,581,1032,3,"[(613, 303), (620, 303), (620, 315), (613, 315)]",0.49,0,"[(613, 303), (620, 303), (620, 315), (613, 315)]",0.49,0,"[(613, 303), (620, 303), (620, 315), (613, 315)]",0.49,[2],False,None,0
12,0,581,1032,4,"[(638, 301), (766, 300), (766, 314), (638, 315)]",0.63,0,"[(638, 301), (766, 300), (766, 314), (638, 315)]",0.63,0,"[(638, 301), (766, 300), (766, 314), (638, 315)]",0.63,"[7, 9, 0, 8, 9, 0, 0, 9, 7]",False,None,0
13,0,581,1032,5,"[(308, 326), (508, 322), (509, 361), (309, 365)]",0.84,0,"[(308, 326), (508, 322), (508, 342), (308, 346)]",0.78,0,"[(308, 326), (377, 325), (377, 345), (308, 346)]",0.99,"[P, R, E, C, I, O]",False,None,0
14,0,581,1032,5,"[(308, 326), (508, 322), (509, 361), (309, 365)]",0.84,0,"[(308, 326), (508, 322), (508, 342), (308, 346)]",0.78,1,"[(394, 325), (399, 325), (399, 344), (394, 344)]",0.94,[X],False,None,0
15,0,581,1032,5,"[(308, 326), (508, 322), (509, 361), (309, 365)]",0.84,0,"[(308, 326), (508, 322), (508, 342), (308, 346)]",0.78,2,"[(410, 324), (430, 324), (430, 344), (410, 344)]",0.95,"[L, T]",False,None,0
16,0,581,1032,5,"[(308, 326), (508, 322), (509, 361), (309, 365)]",0.84,0,"[(308, 326), (508, 322), (508, 342), (308, 346)]",0.78,3,"[(431, 324), (436, 324), (436, 343), (431, 343)]",0.45,[.],False,None,0
17,0,581,1032,5,"[(308, 326), (508, 322), (509, 361), (309, 365)]",0.84,0,"[(308, 326), (508, 322), (508, 342), (308, 346)]",0.78,4,"[(443, 324), (448, 324), (448, 343), (443, 343)]",0.85,[$],True,0,0
18,0,581,1032,5,"[(308, 326), (508, 322), (509, 361), (309, 365)]",0.84,0,"[(308, 326), (508, 322), (508, 342), (308, 346)]",0.78,5,"[(461, 323), (479, 323), (479, 343), (461, 343)]",0.69,"[1, ., 9]",False,None,0
19,0,581,1032,5,"[(308, 326), (508, 322), (509, 361), (309, 365)]",0.84,0,"[(308, 326), (508, 322), (508, 342), (308, 346)]",0.78,6,"[(481, 323), (486, 323), (486, 342), (481, 342)]",0.91,[.],False,None,0
20,0,581,1032,5,"[(308, 326), (508, 322), (509, 361), (309, 365)]",0.84,0,"[(308, 326), (508, 322), (508, 342), (308, 346)]",0.78,7,"[(487, 323), (492, 323), (492, 342), (487, 342)]",0.06,[-],False,None,0
21,0,581,1032,5,"[(308, 326), (508, 322), (509, 361), (309, 365)]",0.84,0,"[(308, 326), (508, 322), (508, 342), (308, 346)]",0.78,8,"[(490, 323), (508, 323), (508, 342), (490, 342)]",0.46,"[1, 9]",False,None,0
22,0,581,1032,5,"[(308, 326), (508, 322), (509, 361), (309, 365)]",0.84,1,"[(346, 348), (503, 344), (503, 360), (346, 364)]",0.92,0,"[(346, 348), (401, 347), (401, 363), (346, 364)]",0.99,"[O, R, I, G, E, N]",False,None,0
23,0,581,1032,5,"[(308, 326), (508, 322), (509, 361), (309, 365)]",0.84,1,"[(346, 348), (503, 344), (503, 360), (346, 364)]",0.92,1,"[(407, 347), (410, 347), (410, 362), (407, 362)]",0.99,[:],False,None,0
24,0,581,1032,5,"[(308, 326), (508, 322), (509, 361), (309, 365)]",0.84,1,"[(346, 348), (503, 344), (503, 360), (346, 364)]",0.92,2,"[(414, 346), (503, 344), (503, 360), (414, 362)]",0.87,"[A, F, G, E, H, ', I, N, S]",False,None,0
25,0,581,1032,6,"[(640, 328), (775, 325), (776, 359), (641, 362)]",0.71,0,"[(640, 328), (775, 325), (776, 359), (641, 362)]",0.71,0,"[(685, 327), (775, 326), (775, 341), (685, 342)]",0.76,"[1, 2, 1, 1, 0, 1, 0, 1, 0]",False,None,0
26,0,581,1032,6,"[(640, 328), (775, 325), (776, 359), (641, 362)]",0.71,0,"[(640, 328), (775, 325), (776, 359), (641, 362)]",0.71,1,"[(640, 347), (676, 346), (676, 361), (640, 362)]",0.60,"[I, m, p, r, e]",False,None,0
27,0,581,1032,6,"[(640, 328), (775, 325), (776, 359), (641, 362)]",0.71,0,"[(640, 328), (775, 325), (776, 359), (641, 362)]",0.71,2,"[(698, 345), (770, 343), (770, 358), (698, 360)]",0.72,"[2, 8, /, 0, 7, /, 2, 0, 0, 0]",False,None,0

In [46]:
df.loc[('9.jpg', 9), 'y'] = 1

In [47]:
df.xs('10.jpg', level='file')

,n_page,page_height,page_width,n_block,block_vert,block_confidence,n_paragraph,paragraph_vert,paragraph_confidence,n_word,word_vert,word_confidence,text,symbol_search_pos,n_symbol_search_find,y
index,,,,,,,,,,,,,,,,
0,0,719,1280,0,"[(581, 284), (936, 266), (938, 315), (584, 333)]",0.93,0,"[(581, 284), (936, 266), (938, 315), (584, 333)]",0.93,0,"[(581, 285), (674, 280), (675, 302), (582, 307)]",0.99,"[G, a, s, e, o, s, a]",False,None,0
1,0,719,1280,0,"[(581, 284), (936, 266), (938, 315), (584, 333)]",0.93,0,"[(581, 284), (936, 266), (938, 315), (584, 333)]",0.93,1,"[(688, 279), (745, 276), (746, 298), (689, 301)]",0.99,"[C, O, C, A]",False,None,0
2,0,719,1280,0,"[(581, 284), (936, 266), (938, 315), (584, 333)]",0.93,0,"[(581, 284), (936, 266), (938, 315), (584, 333)]",0.93,2,"[(755, 276), (812, 273), (813, 294), (756, 297)]",0.80,"[C, O, L, A]",False,None,0
3,0,719,1280,0,"[(581, 284), (936, 266), (938, 315), (584, 333)]",0.93,0,"[(581, 284), (936, 266), (938, 315), (584, 333)]",0.93,3,"[(830, 272), (873, 270), (874, 291), (831, 293)]",0.95,"[B, O, T]",False,None,0
4,0,719,1280,0,"[(581, 284), (936, 266), (938, 315), (584, 333)]",0.93,0,"[(581, 284), (936, 266), (938, 315), (584, 333)]",0.93,4,"[(881, 269), (885, 269), (886, 290), (882, 290)]",0.90,[:],False,None,0
5,0,719,1280,0,"[(581, 284), (936, 266), (938, 315), (584, 333)]",0.93,0,"[(581, 284), (936, 266), (938, 315), (584, 333)]",0.93,5,"[(887, 269), (910, 268), (911, 289), (888, 290)]",0.92,"[2, ., 2]",False,None,0
6,0,719,1280,0,"[(581, 284), (936, 266), (938, 315), (584, 333)]",0.93,0,"[(581, 284), (936, 266), (938, 315), (584, 333)]",0.93,6,"[(920, 267), (932, 266), (933, 287), (921, 288)]",0.85,"[I, t]",False,None,0
7,0,719,1280,0,"[(581, 284), (936, 266), (938, 315), (584, 333)]",0.93,0,"[(581, 284), (936, 266), (938, 315), (584, 333)]",0.93,7,"[(934, 267), (936, 267), (937, 288), (935, 288)]",0.42,[.],False,None,0
8,0,719,1280,0,"[(581, 284), (936, 266), (938, 315), (584, 333)]",0.93,0,"[(581, 284), (936, 266), (938, 315), (584, 333)]",0.93,8,"[(584, 308), (715, 303), (716, 327), (585, 332)]",0.99,"[D, e, s, c, a, r, t, a, b, l, e]",False,None,0
9,0,719,1280,1,"[(677, 332), (814, 343), (807, 419), (671, 408)]",0.91,0,"[(677, 332), (814, 343), (807, 419), (671, 408)]",0.91,0,"[(677, 332), (697, 334), (691, 408), (671, 407)]",0.73,[$],True,0,0
10,0,719,1280,1,"[(677, 332), (814, 343), (807, 419), (671, 408)]",0.91,0,"[(677, 332), (814, 343), (807, 419), (671, 408)]",0.91,1,"[(707, 334), (814, 343), (807, 418), (701, 410)]",0.98,"[1, 5, 2]",False,None,0
11,0,719,1280,2,"[(865, 397), (1001, 390), (1004, 444), (868, 4...",0.85,0,"[(865, 397), (996, 391), (997, 406), (866, 412)]",0.76,0,"[(865, 397), (996, 391), (997, 406), (866, 412)]",0.76,"[7, 7, 9, 0, 8, 9, 5, 0, e, 9, s, 7]",False,None,0
12,0,719,1280,2,"[(865, 397), (1001, 390), (1004, 444), (868, 4...",0.85,1,"[(889, 419), (1002, 412), (1004, 443), (891, 4...",0.88,0,"[(929, 417), (1002, 413), (1003, 427), (930, 4...",0.88,"[1, 2, 1, 1, 0, 1, 0, 1, 0, 0, 9]",False,None,0
13,0,719,1280,2,"[(865, 397), (1001, 390), (1004, 444), (868, 4...",0.85,1,"[(889, 419), (1002, 412), (1004, 443), (891, 4...",0.88,1,"[(890, 436), (931, 433), (932, 446), (891, 449)]",0.83,"[I, n, g, r, e, s, o]",False,None,0
14,0,719,1280,2,"[(865, 397), (1001, 390), (1004, 444), (868, 4...",0.85,1,"[(889, 419), (1002, 412), (1004, 443), (891, 4...",0.88,2,"[(933, 433), (935, 433), (936, 446), (934, 446)]",0.93,[:],False,None,0
15,0,719,1280,2,"[(865, 397), (1001, 390), (1004, 444), (868, 4...",0.85,1,"[(889, 419), (1002, 412), (1004, 443), (891, 4...",0.88,3,"[(939, 433), (1001, 429), (1002, 443), (940, 4...",0.92,"[2, 8, /, 0, 7, /, 2, 0, 2, 0]",False,None,0
16,0,719,1280,3,"[(614, 428), (776, 419), (778, 452), (616, 461)]",0.92,0,"[(614, 428), (776, 419), (777, 436), (615, 445)]",0.89,0,"[(614, 428), (672, 425), (673, 442), (615, 445)]",0.99,"[P, R, E, C, I, O]",False,None,0
17,0,719,1280,3,"[(614, 428), (776, 419), (778, 452), (616, 461)]",0.92,0,"[(614, 428), (776, 419), (777, 436), (615, 445)]",0.89,1,"[(680, 424), (686, 424), (687, 440), (681, 440)]",0.98,[X],False,None,0
18,0,719,1280,3,"[(614, 428), (776, 419), (778, 452), (616, 461)]",0.92,0,"[(614, 428), (776, 419), (777, 436), (615, 445)]",0.89,2,"[(694, 424), (710, 423), (711, 439), (695, 440)]",0.92,"[L, T]",False,None,0
19,0,719,1280,3,"[(614, 428), (776, 419), (778, 452), (616, 461)]",0.92,0,"[(614, 428), (776, 419), (777, 436), (615, 445)]",0.89,3,"[(712, 423), (714, 423), (715, 439), (713, 439)]",0.81,[.],False,None,0
20,0,719,1280,3,"[(614, 428), (776, 419), (778, 452), (616, 461)]",0.92,0,"[(614, 428), (776, 419), (777, 436), (615, 445)]",0.89,4,"[(723, 422), (728, 422), (729, 438), (724, 438)]",0.88,[$],True,0,0
21,0,719,1280,3,"[(614, 428), (776, 419), (778, 452), (616, 461)]",0.92,0,"[(614, 428), (776, 419), (777, 436), (615, 445)]",0.89,5,"[(737, 421), (776, 419), (777, 435), (738, 437)]",0.79,"[1, ., 9, ., 4, 9]",False,None,0
22,0,719,1280,3,"[(614, 428), (776, 419), (778, 452), (616, 461)]",0.92,1,"[(643, 445), (771, 438), (772, 452), (644, 459)]",0.96,0,"[(643, 445), (690, 443), (691, 457), (644, 459)]",0.99,"[O, R, I, G, E, N]",False,None,0
23,0,719,1280,3,"[(614, 428), (776, 419), (778, 452), (616, 461)]",0.92,1,"[(643, 445), (771, 438), (772, 452), (644, 459)]",0.96,1,"[(694, 443), (697, 443), (698, 456), (695, 456)]",0.99,[:],False,None,0
24,0,719,1280,3,"[(614, 428), (776, 419), (778, 452), (616, 461)]",0.92,1,"[(643, 445), (771, 438), (772, 452), (644, 459)]",0.96,2,"[(698, 442), (771, 438), (772, 452), (699, 456)]",0.93,"[A, F, G, E, N, T, I, N, A]",False,None,0
25,0,719,1280,4,"[(310, 587), (303, 728), (188, 722), (195, 582)]",0.82,0,"[(310, 587), (303, 728), (188, 722), (195, 582)]",0.82,0,"[(310, 587), (304, 707), (189, 701), (195, 582)]",0.98,"[C, o, c, a]",False,None,0
26,0,719,1280,4,"[(310, 587), (303, 728), (188, 722), (195, 582)]",0.82,0,"[(310, 587), (303, 728), (188, 722), (195, 582)]",0.82,1,"[(304, 709), (303, 728), (189, 723), (190, 704)]",0.21,[.],False,None,0
27,0,719,1280,5,"[(354, 628), (356, 699), (336, 700), (334, 629)]",0.99,0,"[(354, 628), (356, 699), (336, 700), (334, 629)]",0.99,0,"[(354, 628), (356, 699), (336, 700), (334, 629)]",0.99,"[S, A, B, O, R]",False,None,0

In [48]:
df.loc[('10.jpg', 10), 'y'] = 1

In [49]:
df.xs('11.jpg', level='file')

,n_page,page_height,page_width,n_block,block_vert,block_confidence,n_paragraph,paragraph_vert,paragraph_confidence,n_word,word_vert,word_confidence,text,symbol_search_pos,n_symbol_search_find,y
index,,,,,,,,,,,,,,,,
0,0,581,1032,0,"[(85, 108), (759, 90), (762, 216), (88, 234)]",0.93,0,"[(85, 108), (242, 104), (244, 178), (87, 182)]",0.99,0,"[(85, 109), (210, 104), (211, 141), (86, 146)]",0.99,"[p, r, e, c, i, o, s]",False,None,0
1,0,581,1032,0,"[(85, 108), (759, 90), (762, 216), (88, 234)]",0.93,0,"[(85, 108), (242, 104), (244, 178), (87, 182)]",0.99,1,"[(88, 141), (243, 138), (244, 177), (89, 180)]",0.99,"[c, u, i, d, a, d, o, s]",False,None,0
2,0,581,1032,0,"[(85, 108), (759, 90), (762, 216), (88, 234)]",0.93,1,"[(166, 192), (761, 177), (762, 216), (167, 231)]",0.90,0,"[(166, 193), (309, 189), (310, 227), (167, 231)]",0.99,"[g, a, s, e, o, s, a]",False,None,0
3,0,581,1032,0,"[(85, 108), (759, 90), (762, 216), (88, 234)]",0.93,1,"[(166, 192), (761, 177), (762, 216), (167, 231)]",0.90,1,"[(325, 189), (416, 187), (417, 224), (326, 226)]",0.99,"[C, O, C, A]",False,None,0
4,0,581,1032,0,"[(85, 108), (759, 90), (762, 216), (88, 234)]",0.93,1,"[(166, 192), (761, 177), (762, 216), (167, 231)]",0.90,2,"[(432, 186), (508, 184), (509, 222), (433, 224)]",1.00,"[C, O, L, A]",False,None,0
5,0,581,1032,0,"[(85, 108), (759, 90), (762, 216), (88, 234)]",0.93,1,"[(166, 192), (761, 177), (762, 216), (167, 231)]",0.90,3,"[(533, 183), (604, 181), (605, 219), (534, 221)]",0.87,"[1, ., 2, 5, -, 1]",False,None,0
6,0,581,1032,0,"[(85, 108), (759, 90), (762, 216), (88, 234)]",0.93,1,"[(166, 192), (761, 177), (762, 216), (167, 231)]",0.90,4,"[(607, 182), (617, 182), (618, 219), (608, 219)]",0.07,[+],False,None,0
7,0,581,1032,0,"[(85, 108), (759, 90), (762, 216), (88, 234)]",0.93,1,"[(166, 192), (761, 177), (762, 216), (167, 231)]",0.90,5,"[(625, 181), (681, 180), (682, 217), (626, 218)]",0.75,"[B, O, T]",False,None,0
8,0,581,1032,0,"[(85, 108), (759, 90), (762, 216), (88, 234)]",0.93,1,"[(166, 192), (761, 177), (762, 216), (167, 231)]",0.90,6,"[(695, 179), (740, 178), (741, 216), (696, 217)]",0.97,"[1, ., 2, 5]",False,None,0
9,0,581,1032,0,"[(85, 108), (759, 90), (762, 216), (88, 234)]",0.93,1,"[(166, 192), (761, 177), (762, 216), (167, 231)]",0.90,7,"[(756, 178), (761, 178), (762, 215), (757, 215)]",0.91,[/],False,None,0
10,0,581,1032,1,"[(287, 117), (425, 114), (426, 172), (288, 175)]",0.94,0,"[(287, 117), (425, 114), (426, 172), (288, 175)]",0.94,0,"[(287, 117), (327, 116), (327, 132), (287, 133)]",0.95,"[w, w, w]",False,None,0
11,0,581,1032,1,"[(287, 117), (425, 114), (426, 172), (288, 175)]",0.94,0,"[(287, 117), (425, 114), (426, 172), (288, 175)]",0.94,1,"[(291, 133), (425, 131), (425, 154), (291, 156)]",0.96,"[p, r, e, c, i, o, s, c, u, i, d, a, d, o, s]",False,None,0
12,0,581,1032,1,"[(287, 117), (425, 114), (426, 172), (288, 175)]",0.94,0,"[(287, 117), (425, 114), (426, 172), (288, 175)]",0.94,2,"[(293, 156), (343, 156), (343, 174), (293, 174)]",0.88,"[g, o, b, ., a, r]",False,None,0
13,0,581,1032,2,"[(501, 133), (647, 135), (647, 156), (501, 154)]",0.70,0,"[(501, 133), (647, 135), (647, 156), (501, 154)]",0.70,0,"[(501, 133), (551, 134), (551, 155), (501, 154)]",0.07,"[H, o, m, e]",False,None,0
14,0,581,1032,2,"[(501, 133), (647, 135), (647, 156), (501, 154)]",0.70,0,"[(501, 133), (647, 135), (647, 156), (501, 154)]",0.70,1,"[(560, 134), (613, 135), (613, 156), (560, 155)]",0.85,"[A, r, g, e, n, t, i, n, a]",False,None,0
15,0,581,1032,2,"[(501, 133), (647, 135), (647, 156), (501, 154)]",0.70,0,"[(501, 133), (647, 135), (647, 156), (501, 154)]",0.70,2,"[(618, 135), (647, 135), (647, 156), (618, 156)]",0.91,"[u, n, i, d, a]",False,None,0
16,0,581,1032,3,"[(164, 272), (274, 269), (274, 281), (164, 284)]",0.96,0,"[(164, 272), (274, 269), (274, 281), (164, 284)]",0.96,0,"[(164, 272), (202, 271), (202, 283), (164, 284)]",0.99,"[O, R, I, G, E, N]",False,None,0
17,0,581,1032,3,"[(164, 272), (274, 269), (274, 281), (164, 284)]",0.96,0,"[(164, 272), (274, 269), (274, 281), (164, 284)]",0.96,1,"[(207, 271), (208, 271), (208, 282), (207, 282)]",0.88,[:],False,None,0
18,0,581,1032,3,"[(164, 272), (274, 269), (274, 281), (164, 284)]",0.96,0,"[(164, 272), (274, 269), (274, 281), (164, 284)]",0.96,2,"[(212, 271), (274, 270), (274, 282), (212, 283)]",0.94,"[A, R, G, E, N, T, I, N, A]",False,None,0
19,0,581,1032,4,"[(382, 274), (622, 245), (633, 330), (392, 359)]",0.99,0,"[(382, 274), (622, 245), (633, 330), (392, 359)]",0.99,0,"[(382, 274), (401, 272), (411, 356), (392, 358)]",0.99,[$],True,0,0
20,0,581,1032,4,"[(382, 274), (622, 245), (633, 330), (392, 359)]",0.99,0,"[(382, 274), (622, 245), (633, 330), (392, 359)]",0.99,1,"[(437, 267), (623, 244), (633, 330), (447, 352)]",0.99,"[8, 7, ., 5, 0]",False,None,0
21,0,581,1032,5,"[(458, 361), (552, 358), (552, 372), (458, 375)]",0.89,0,"[(458, 361), (552, 358), (552, 372), (458, 375)]",0.89,0,"[(458, 361), (495, 360), (495, 374), (458, 375)]",0.99,"[P, R, E, C, I, O]",False,None,0
22,0,581,1032,5,"[(458, 361), (552, 358), (552, 372), (458, 375)]",0.89,0,"[(458, 361), (552, 358), (552, 372), (458, 375)]",0.89,1,"[(500, 360), (512, 360), (512, 373), (500, 373)]",0.96,"[X, L]",False,None,0
23,0,581,1032,5,"[(458, 361), (552, 358), (552, 372), (458, 375)]",0.89,0,"[(458, 361), (552, 358), (552, 372), (458, 375)]",0.89,2,"[(519, 359), (552, 358), (552, 372), (519, 373)]",0.76,"[5, 2, 0, ., 0, 0]",False,None,0
24,0,581,1032,6,"[(11, 348), (103, 347), (105, 473), (13, 474)]",0.97,0,"[(11, 348), (103, 347), (105, 473), (13, 474)]",0.97,0,"[(11, 348), (103, 347), (105, 473), (13, 474)]",0.97,"[o, l, u]",False,None,0
25,0,581,1032,7,"[(176, 389), (475, 373), (476, 397), (177, 413)]",0.97,0,"[(176, 389), (475, 373), (476, 397), (177, 413)]",0.97,0,"[(176, 389), (233, 386), (234, 409), (177, 412)]",0.97,"[S, U, M, Á]",False,None,0
26,0,581,1032,7,"[(176, 389), (475, 373), (476, 397), (177, 413)]",0.97,0,"[(176, 389), (475, 373), (476, 397), (177, 413)]",0.97,1,"[(248, 385), (276, 384), (277, 408), (249, 409)]",0.90,"[6, 1, 3]",False,None,0
27,0,581,1032,7,"[(176, 389), (475, 373), (476, 397), (177, 413)]",0.97,0,"[(176, 389), (475, 373), (476, 397), (177, 413)]",0.97,2,"[(285, 383), (359, 379), (360, 403), (286, 407)]",0.99,"[P, U, N, T, O, S]",False,None,0
28,0,581,1032,7,"[(176, 389), (475, 373), (476, 397), (177, 413)]",0.97,0,"[(176, 389), (475, 373), (476, 397), (177, 413)]",0.97,3,"[(367, 379), (431, 376), (432, 400), (368, 403)]",0.99,"[J, U, M, B, O]",False,None,0
29,0,581,1032,7,"[(176, 389), (475, 373), (476, 397), (177, 413)]",0.97,0,"[(176, 389), (475, 373), (476, 397), (177, 413)]",0.97,4,"[(439, 375), (475, 373), (476, 397), (440, 399)]",0.98,"[M, Á, S]",False,None,0

In [50]:
df.loc[('11.jpg', 20), 'y'] = 1

In [51]:
df.xs('12.jpg', level='file')

,n_page,page_height,page_width,n_block,block_vert,block_confidence,n_paragraph,paragraph_vert,paragraph_confidence,n_word,word_vert,word_confidence,text,symbol_search_pos,n_symbol_search_find,y
index,,,,,,,,,,,,,,,,
0,0,581,1032,0,"[(152, 101), (749, 119), (745, 234), (149, 216)]",0.94,0,"[(152, 101), (289, 105), (287, 171), (150, 167)]",0.99,0,"[(152, 101), (263, 104), (262, 142), (151, 139)]",0.99,"[p, r, e, c, i, o, s]",False,None,0
1,0,581,1032,0,"[(152, 101), (749, 119), (745, 234), (149, 216)]",0.94,0,"[(152, 101), (289, 105), (287, 171), (150, 167)]",0.99,1,"[(152, 133), (288, 137), (287, 171), (151, 167)]",0.99,"[c, u, i, d, a, d, o, s]",False,None,0
2,0,581,1032,0,"[(152, 101), (749, 119), (745, 234), (149, 216)]",0.94,1,"[(217, 183), (747, 199), (746, 234), (216, 218)]",0.92,0,"[(217, 183), (344, 187), (343, 221), (216, 217)]",0.99,"[g, a, s, e, o, s, a]",False,None,0
3,0,581,1032,0,"[(152, 101), (749, 119), (745, 234), (149, 216)]",0.94,1,"[(217, 183), (747, 199), (746, 234), (216, 218)]",0.92,1,"[(358, 188), (439, 190), (438, 223), (357, 221)]",0.99,"[C, O, C, A]",False,None,0
4,0,581,1032,0,"[(152, 101), (749, 119), (745, 234), (149, 216)]",0.94,1,"[(217, 183), (747, 199), (746, 234), (216, 218)]",0.92,2,"[(451, 191), (523, 193), (522, 226), (450, 224)]",1.00,"[C, O, L, A]",False,None,0
5,0,581,1032,0,"[(152, 101), (749, 119), (745, 234), (149, 216)]",0.94,1,"[(217, 183), (747, 199), (746, 234), (216, 218)]",0.92,3,"[(534, 193), (579, 194), (578, 228), (533, 227)]",0.98,"[1, ., 2, 5]",False,None,0
6,0,581,1032,0,"[(152, 101), (749, 119), (745, 234), (149, 216)]",0.94,1,"[(217, 183), (747, 199), (746, 234), (216, 218)]",0.92,4,"[(586, 195), (594, 195), (593, 228), (585, 228)]",0.99,[-],False,None,0
7,0,581,1032,0,"[(152, 101), (749, 119), (745, 234), (149, 216)]",0.94,1,"[(217, 183), (747, 199), (746, 234), (216, 218)]",0.92,5,"[(601, 196), (612, 196), (611, 229), (600, 229)]",0.90,[I],False,None,0
8,0,581,1032,0,"[(152, 101), (749, 119), (745, 234), (149, 216)]",0.94,1,"[(217, 183), (747, 199), (746, 234), (216, 218)]",0.92,6,"[(625, 196), (676, 198), (675, 232), (624, 230)]",0.69,"[B, O, T]",False,None,0
9,0,581,1032,0,"[(152, 101), (749, 119), (745, 234), (149, 216)]",0.94,1,"[(217, 183), (747, 199), (746, 234), (216, 218)]",0.92,7,"[(688, 198), (730, 199), (729, 233), (687, 232)]",0.92,"[1, ., 2, 5]",False,None,0
10,0,581,1032,0,"[(152, 101), (749, 119), (745, 234), (149, 216)]",0.94,1,"[(217, 183), (747, 199), (746, 234), (216, 218)]",0.92,8,"[(743, 200), (747, 200), (746, 233), (742, 233)]",0.24,[/],False,None,0
11,0,581,1032,1,"[(328, 121), (450, 126), (448, 177), (326, 172)]",0.97,0,"[(328, 121), (450, 126), (448, 177), (326, 172)]",0.97,0,"[(328, 121), (365, 122), (365, 138), (328, 137)]",0.92,"[w, w, w]",False,None,0
12,0,581,1032,1,"[(328, 121), (450, 126), (448, 177), (326, 172)]",0.97,0,"[(328, 121), (450, 126), (448, 177), (326, 172)]",0.97,1,"[(332, 137), (449, 144), (448, 162), (331, 156)]",0.98,"[p, r, e, c, i, o, s, c, u, i, d, a, d, o, s]",False,None,0
13,0,581,1032,1,"[(328, 121), (450, 126), (448, 177), (326, 172)]",0.97,0,"[(328, 121), (450, 126), (448, 177), (326, 172)]",0.97,2,"[(331, 155), (376, 156), (375, 173), (330, 172)]",0.96,"[g, o, b, a, r]",False,None,0
14,0,581,1032,2,"[(569, 151), (647, 155), (646, 172), (568, 168)]",0.95,0,"[(569, 151), (647, 155), (646, 172), (568, 168)]",0.95,0,"[(569, 151), (615, 153), (614, 170), (568, 168)]",0.94,"[A, r, g, e, n, t, i, n, a]",False,None,0
15,0,581,1032,2,"[(569, 151), (647, 155), (646, 172), (568, 168)]",0.95,0,"[(569, 151), (647, 155), (646, 172), (568, 168)]",0.95,1,"[(621, 154), (647, 155), (646, 172), (620, 171)]",0.96,"[u, n, i, d, a]",False,None,0
16,0,581,1032,3,"[(210, 254), (308, 257), (307, 271), (210, 268)]",0.95,0,"[(210, 254), (308, 257), (307, 271), (210, 268)]",0.95,0,"[(210, 254), (249, 255), (249, 268), (210, 267)]",0.99,"[O, R, I, G, E, N]",False,None,0
17,0,581,1032,3,"[(210, 254), (308, 257), (307, 271), (210, 268)]",0.95,0,"[(210, 254), (308, 257), (307, 271), (210, 268)]",0.95,1,"[(253, 256), (308, 258), (308, 271), (253, 269)]",0.93,"[A, R, G, E, N, T, I, N, A]",False,None,0
18,0,581,1032,4,"[(401, 271), (619, 255), (625, 330), (407, 346)]",0.97,0,"[(401, 271), (619, 255), (625, 330), (407, 346)]",0.97,0,"[(401, 271), (420, 270), (425, 344), (407, 346)]",0.99,[$],True,0,0
19,0,581,1032,4,"[(401, 271), (619, 255), (625, 330), (407, 346)]",0.97,0,"[(401, 271), (619, 255), (625, 330), (407, 346)]",0.97,1,"[(451, 267), (620, 255), (625, 329), (457, 342)]",0.97,"[8, 7, ., 5, 0]",False,None,0
20,0,581,1032,5,"[(212, 349), (551, 351), (551, 386), (212, 384)]",0.91,0,"[(212, 349), (551, 351), (551, 386), (212, 384)]",0.91,0,"[(468, 351), (551, 353), (551, 366), (468, 364)]",0.82,"[P, R, E, C, I, O, X, L, 5, 7, 0, ., 0, 0]",False,None,0
21,0,581,1032,5,"[(212, 349), (551, 351), (551, 386), (212, 384)]",0.91,0,"[(212, 349), (551, 351), (551, 386), (212, 384)]",0.91,1,"[(212, 364), (263, 364), (263, 384), (212, 384)]",0.97,"[S, U, M, Á]",False,None,0
22,0,581,1032,5,"[(212, 349), (551, 351), (551, 386), (212, 384)]",0.91,0,"[(212, 349), (551, 351), (551, 386), (212, 384)]",0.91,2,"[(277, 364), (302, 364), (302, 384), (277, 384)]",0.90,"[6, 1, 3]",False,None,0
23,0,581,1032,5,"[(212, 349), (551, 351), (551, 386), (212, 384)]",0.91,0,"[(212, 349), (551, 351), (551, 386), (212, 384)]",0.91,3,"[(310, 364), (377, 364), (377, 384), (310, 384)]",0.99,"[P, U, N, T, O, S]",False,None,0
24,0,581,1032,5,"[(212, 349), (551, 351), (551, 386), (212, 384)]",0.91,0,"[(212, 349), (551, 351), (551, 386), (212, 384)]",0.91,4,"[(385, 364), (442, 364), (442, 384), (385, 384)]",0.99,"[J, U, M, B, O]",False,None,0
25,0,581,1032,5,"[(212, 349), (551, 351), (551, 386), (212, 384)]",0.91,0,"[(212, 349), (551, 351), (551, 386), (212, 384)]",0.91,5,"[(450, 364), (482, 364), (482, 385), (450, 385)]",0.98,"[M, Á, S]",False,None,0
26,0,581,1032,6,"[(-6, 329), (138, 328), (139, 446), (-5, 447)]",0.71,0,"[(-6, 329), (138, 328), (139, 446), (-5, 447)]",0.71,0,"[(-6, 329), (138, 328), (139, 446), (-5, 447)]",0.71,"[C, o, l, d]",False,None,0

In [52]:
df.loc[('12.jpg', 19), 'y'] = 1

In [53]:
df.xs('13.jpg', level='file')

,n_page,page_height,page_width,n_block,block_vert,block_confidence,n_paragraph,paragraph_vert,paragraph_confidence,n_word,word_vert,word_confidence,text,symbol_search_pos,n_symbol_search_find,y
index,,,,,,,,,,,,,,,,
0,0,581,1032,0,"[(259, 165), (677, 161), (678, 220), (260, 224)]",0.95,0,"[(259, 165), (677, 161), (678, 220), (260, 224)]",0.95,0,"[(262, 165), (373, 164), (373, 193), (262, 194)]",0.97,"[G, a, s, e, o, s, a]",False,None,0
1,0,581,1032,0,"[(259, 165), (677, 161), (678, 220), (260, 224)]",0.95,0,"[(259, 165), (677, 161), (678, 220), (260, 224)]",0.95,1,"[(385, 164), (455, 163), (455, 192), (385, 193)]",0.99,"[C, O, C, A]",False,None,0
2,0,581,1032,0,"[(259, 165), (677, 161), (678, 220), (260, 224)]",0.95,0,"[(259, 165), (677, 161), (678, 220), (260, 224)]",0.95,2,"[(467, 163), (532, 162), (532, 191), (467, 192)]",0.83,"[C, O, L, A]",False,None,0
3,0,581,1032,0,"[(259, 165), (677, 161), (678, 220), (260, 224)]",0.95,0,"[(259, 165), (677, 161), (678, 220), (260, 224)]",0.95,3,"[(553, 162), (601, 162), (601, 191), (553, 191)]",0.97,"[B, O, T]",False,None,0
4,0,581,1032,0,"[(259, 165), (677, 161), (678, 220), (260, 224)]",0.95,0,"[(259, 165), (677, 161), (678, 220), (260, 224)]",0.95,4,"[(612, 162), (645, 162), (645, 190), (612, 190)]",0.97,"[2, ., 2]",False,None,0
5,0,581,1032,0,"[(259, 165), (677, 161), (678, 220), (260, 224)]",0.95,0,"[(259, 165), (677, 161), (678, 220), (260, 224)]",0.95,5,"[(658, 162), (671, 162), (671, 190), (658, 190)]",0.91,"[I, t]",False,None,0
6,0,581,1032,0,"[(259, 165), (677, 161), (678, 220), (260, 224)]",0.95,0,"[(259, 165), (677, 161), (678, 220), (260, 224)]",0.95,6,"[(674, 162), (677, 162), (677, 190), (674, 190)]",0.81,[.],False,None,0
7,0,581,1032,0,"[(259, 165), (677, 161), (678, 220), (260, 224)]",0.95,0,"[(259, 165), (677, 161), (678, 220), (260, 224)]",0.95,7,"[(260, 194), (430, 194), (430, 222), (260, 222)]",0.97,"[D, e, s, c, a, r, t, a, b, l, e]",False,None,0
8,0,581,1032,1,"[(376, 243), (759, 248), (758, 320), (375, 315)]",0.46,0,"[(376, 243), (759, 248), (758, 320), (375, 315)]",0.46,0,"[(376, 244), (396, 244), (395, 315), (375, 315)]",0.99,[$],True,0,0
9,0,581,1032,1,"[(376, 243), (759, 248), (758, 320), (375, 315)]",0.46,0,"[(376, 243), (759, 248), (758, 320), (375, 315)]",0.46,1,"[(403, 244), (500, 245), (499, 316), (402, 315)]",0.97,"[1, 5, 2]",False,None,0
10,0,581,1032,1,"[(376, 243), (759, 248), (758, 320), (375, 315)]",0.46,0,"[(376, 243), (759, 248), (758, 320), (375, 315)]",0.46,2,"[(514, 246), (541, 246), (540, 317), (513, 317)]",0.35,[.],False,None,0
11,0,581,1032,1,"[(376, 243), (759, 248), (758, 320), (375, 315)]",0.46,0,"[(376, 243), (759, 248), (758, 320), (375, 315)]",0.46,3,"[(612, 247), (645, 247), (644, 318), (611, 318)]",0.09,[I],False,None,0
12,0,581,1032,1,"[(376, 243), (759, 248), (758, 320), (375, 315)]",0.46,0,"[(376, 243), (759, 248), (758, 320), (375, 315)]",0.46,4,"[(661, 247), (759, 248), (758, 320), (660, 319)]",0.16,"[U, N, D, E, R]",False,None,0
13,0,581,1032,2,"[(594, 310), (602, 310), (602, 322), (594, 322)]",0.92,0,"[(594, 310), (602, 310), (602, 322), (594, 322)]",0.92,0,"[(594, 310), (602, 310), (602, 322), (594, 322)]",0.92,[7],False,None,0
14,0,581,1032,3,"[(309, 332), (493, 329), (494, 366), (310, 369)]",0.80,0,"[(309, 333), (493, 329), (493, 347), (309, 351)]",0.83,0,"[(309, 333), (376, 332), (376, 350), (309, 351)]",0.99,"[P, R, E, C, I, O]",False,None,0
15,0,581,1032,3,"[(309, 332), (493, 329), (494, 366), (310, 369)]",0.80,0,"[(309, 333), (493, 329), (493, 347), (309, 351)]",0.83,1,"[(385, 332), (417, 331), (417, 348), (385, 349)]",0.91,"[X, L, T]",False,None,0
16,0,581,1032,3,"[(309, 332), (493, 329), (494, 366), (310, 369)]",0.80,0,"[(309, 333), (493, 329), (493, 347), (309, 351)]",0.83,2,"[(433, 331), (439, 331), (439, 348), (433, 348)]",0.86,[$],True,0,0
17,0,581,1032,3,"[(309, 332), (493, 329), (494, 366), (310, 369)]",0.80,0,"[(309, 333), (493, 329), (493, 347), (309, 351)]",0.83,3,"[(451, 330), (468, 330), (468, 347), (451, 347)]",0.69,"[1, 1, 9]",False,None,0
18,0,581,1032,3,"[(309, 332), (493, 329), (494, 366), (310, 369)]",0.80,0,"[(309, 333), (493, 329), (493, 347), (309, 351)]",0.83,4,"[(470, 330), (474, 330), (474, 347), (470, 347)]",0.90,"[,]",False,None,0
19,0,581,1032,3,"[(309, 332), (493, 329), (494, 366), (310, 369)]",0.80,0,"[(309, 333), (493, 329), (493, 347), (309, 351)]",0.83,5,"[(477, 330), (493, 330), (493, 347), (477, 347)]",0.57,"[-, 1, 9]",False,None,0
20,0,581,1032,3,"[(309, 332), (493, 329), (494, 366), (310, 369)]",0.80,1,"[(343, 352), (488, 350), (488, 366), (343, 368)]",0.76,0,"[(343, 352), (395, 351), (395, 367), (343, 368)]",0.97,"[O, R, I, G, E, N]",False,None,0
21,0,581,1032,3,"[(309, 332), (493, 329), (494, 366), (310, 369)]",0.80,1,"[(343, 352), (488, 350), (488, 366), (343, 368)]",0.76,1,"[(400, 352), (403, 352), (403, 367), (400, 367)]",0.95,[:],False,None,0
22,0,581,1032,3,"[(309, 332), (493, 329), (494, 366), (310, 369)]",0.80,1,"[(343, 352), (488, 350), (488, 366), (343, 368)]",0.76,2,"[(408, 351), (488, 350), (488, 366), (408, 367)]",0.58,"[A, F, G, E, L, I, N, A]",False,None,0
23,0,581,1032,4,"[(622, 307), (751, 306), (751, 369), (622, 370)]",0.79,0,"[(622, 307), (744, 306), (744, 323), (622, 324)]",0.71,0,"[(622, 307), (744, 306), (744, 323), (622, 324)]",0.71,"[7, 9, 0, 8, 9, 0, 0, 9, 7]",False,None,0
24,0,581,1032,4,"[(622, 307), (751, 306), (751, 369), (622, 370)]",0.79,1,"[(623, 335), (751, 335), (751, 369), (623, 369)]",0.81,0,"[(666, 335), (751, 335), (751, 348), (666, 348)]",0.83,"[1, 2, 1, 1, 0, 1, 0, 1, 0, 0, 9]",False,None,0
25,0,581,1032,4,"[(622, 307), (751, 306), (751, 369), (622, 370)]",0.79,1,"[(623, 335), (751, 335), (751, 369), (623, 369)]",0.81,1,"[(623, 353), (671, 352), (671, 368), (623, 369)]",0.67,"[I, n, g, r, e, s, o]",False,None,0
26,0,581,1032,4,"[(622, 307), (751, 306), (751, 369), (622, 370)]",0.79,1,"[(623, 335), (751, 335), (751, 369), (623, 369)]",0.81,2,"[(673, 352), (676, 352), (676, 367), (673, 367)]",0.97,[:],False,None,0
27,0,581,1032,4,"[(622, 307), (751, 306), (751, 369), (622, 370)]",0.79,1,"[(623, 335), (751, 335), (751, 369), (623, 369)]",0.81,3,"[(680, 352), (749, 351), (749, 367), (680, 368)]",0.87,"[2, 8, /, 0, 7, /, 2, 0, 2, 0]",False,None,0

In [54]:
df.loc[('13.jpg', 9), 'y'] = 1

In [55]:
df.xs('14.jpg', level='file')

,n_page,page_height,page_width,n_block,block_vert,block_confidence,n_paragraph,paragraph_vert,paragraph_confidence,n_word,word_vert,word_confidence,text,symbol_search_pos,n_symbol_search_find,y
index,,,,,,,,,,,,,,,,
0,0,581,1032,0,"[(308, 136), (737, 140), (737, 162), (308, 158)]",0.85,0,"[(308, 136), (737, 140), (737, 162), (308, 158)]",0.85,0,"[(308, 136), (402, 137), (402, 159), (308, 158)]",0.90,"[g, u, s, e, o, s, a]",False,None,0
1,0,581,1032,0,"[(308, 136), (737, 140), (737, 162), (308, 158)]",0.85,0,"[(308, 136), (737, 140), (737, 162), (308, 158)]",0.85,1,"[(411, 138), (472, 139), (472, 160), (411, 159)]",0.97,"[C, O, C, A]",False,None,0
2,0,581,1032,0,"[(308, 136), (737, 140), (737, 162), (308, 158)]",0.85,0,"[(308, 136), (737, 140), (737, 162), (308, 158)]",0.85,2,"[(485, 138), (538, 138), (538, 160), (485, 160)]",0.97,"[C, O, L, A]",False,None,0
3,0,581,1032,0,"[(308, 136), (737, 140), (737, 162), (308, 158)]",0.85,0,"[(308, 136), (737, 140), (737, 162), (308, 158)]",0.85,3,"[(553, 139), (591, 139), (591, 160), (553, 160)]",0.79,"[1, ., 2, 5]",False,None,0
4,0,581,1032,0,"[(308, 136), (737, 140), (737, 162), (308, 158)]",0.85,0,"[(308, 136), (737, 140), (737, 162), (308, 158)]",0.85,4,"[(598, 139), (603, 139), (603, 160), (598, 160)]",0.92,[-],False,None,0
5,0,581,1032,0,"[(308, 136), (737, 140), (737, 162), (308, 158)]",0.85,0,"[(308, 136), (737, 140), (737, 162), (308, 158)]",0.85,5,"[(607, 139), (612, 139), (612, 160), (607, 160)]",0.23,[i],False,None,0
6,0,581,1032,0,"[(308, 136), (737, 140), (737, 162), (308, 158)]",0.85,0,"[(308, 136), (737, 140), (737, 162), (308, 158)]",0.85,6,"[(626, 139), (671, 139), (671, 161), (626, 161)]",0.79,"[B, O, T]",False,None,0
7,0,581,1032,0,"[(308, 136), (737, 140), (737, 162), (308, 158)]",0.85,0,"[(308, 136), (737, 140), (737, 162), (308, 158)]",0.85,7,"[(679, 140), (737, 141), (737, 162), (679, 161)]",0.79,"[7, ., 2, 5, 7]",False,None,0
8,0,581,1032,1,"[(454, 197), (547, 198), (546, 273), (453, 272)]",0.99,0,"[(454, 197), (547, 198), (546, 273), (453, 272)]",0.99,0,"[(454, 197), (547, 198), (546, 273), (453, 272)]",0.99,"[8, 7]",False,None,0
9,0,581,1032,2,"[(569, 221), (598, 220), (599, 240), (570, 241)]",0.94,0,"[(569, 221), (598, 220), (599, 240), (570, 241)]",0.94,0,"[(569, 221), (598, 220), (599, 240), (570, 241)]",0.94,"[., 5, 0]",False,None,0
10,0,581,1032,3,"[(345, 279), (492, 278), (492, 313), (345, 314)]",0.95,0,"[(345, 279), (488, 278), (488, 296), (345, 297)]",0.95,0,"[(345, 279), (397, 279), (397, 297), (345, 297)]",0.99,"[P, R, E, C, I, O]",False,None,0
11,0,581,1032,3,"[(345, 279), (492, 278), (492, 313), (345, 314)]",0.95,0,"[(345, 279), (488, 278), (488, 296), (345, 297)]",0.95,1,"[(409, 279), (432, 279), (432, 297), (409, 297)]",0.88,"[X, L]",False,None,0
12,0,581,1032,3,"[(345, 279), (492, 278), (492, 313), (345, 314)]",0.95,0,"[(345, 279), (488, 278), (488, 296), (345, 297)]",0.95,2,"[(437, 279), (442, 279), (442, 297), (437, 297)]",0.71,[$],True,0,0
13,0,581,1032,3,"[(345, 279), (492, 278), (492, 313), (345, 314)]",0.95,0,"[(345, 279), (488, 278), (488, 296), (345, 297)]",0.95,3,"[(446, 279), (488, 279), (488, 297), (446, 297)]",0.98,"[7, 0, ., 0, 0]",False,None,0
14,0,581,1032,3,"[(345, 279), (492, 278), (492, 313), (345, 314)]",0.95,1,"[(370, 299), (492, 299), (492, 313), (370, 313)]",0.96,0,"[(370, 299), (415, 299), (415, 313), (370, 313)]",0.99,"[O, R, I, G, E, N]",False,None,0
15,0,581,1032,3,"[(345, 279), (492, 278), (492, 313), (345, 314)]",0.95,1,"[(370, 299), (492, 299), (492, 313), (370, 313)]",0.96,1,"[(424, 299), (492, 299), (492, 313), (424, 313)]",0.93,"[A, R, G, E, N, T, I, N, A]",False,None,0
16,0,581,1032,4,"[(608, 265), (776, 265), (776, 314), (608, 314)]",0.96,0,"[(608, 265), (776, 265), (776, 282), (608, 282)]",0.93,0,"[(608, 265), (624, 265), (624, 282), (608, 282)]",0.99,"[7, 7]",False,None,0
17,0,581,1032,4,"[(608, 265), (776, 265), (776, 314), (608, 314)]",0.96,0,"[(608, 265), (776, 265), (776, 282), (608, 282)]",0.93,1,"[(644, 265), (692, 265), (692, 282), (644, 282)]",0.95,"[9, 0, 8, 9, 5]",False,None,0
18,0,581,1032,4,"[(608, 265), (776, 265), (776, 314), (608, 314)]",0.96,0,"[(608, 265), (776, 265), (776, 282), (608, 282)]",0.93,2,"[(701, 265), (750, 265), (750, 282), (701, 282)]",0.91,"[0, 1, 2, 2, 6]",False,None,0
19,0,581,1032,4,"[(608, 265), (776, 265), (776, 314), (608, 314)]",0.96,0,"[(608, 265), (776, 265), (776, 282), (608, 282)]",0.93,3,"[(768, 265), (776, 265), (776, 282), (768, 282)]",0.89,[6],False,None,0
20,0,581,1032,4,"[(608, 265), (776, 265), (776, 314), (608, 314)]",0.96,1,"[(636, 285), (758, 285), (758, 314), (636, 314)]",0.98,0,"[(680, 285), (757, 285), (757, 299), (680, 299)]",0.97,"[1, 2, 1, 1, 0, 1, 0, 1, 2, 1, 9]",False,None,0
21,0,581,1032,4,"[(608, 265), (776, 265), (776, 314), (608, 314)]",0.96,1,"[(636, 285), (758, 285), (758, 314), (636, 314)]",0.98,1,"[(636, 299), (681, 298), (681, 313), (636, 314)]",0.98,"[I, m, p, r, e, s, o]",False,None,0
22,0,581,1032,4,"[(608, 265), (776, 265), (776, 314), (608, 314)]",0.96,1,"[(636, 285), (758, 285), (758, 314), (636, 314)]",0.98,2,"[(684, 299), (686, 299), (686, 313), (684, 313)]",0.94,[:],False,None,0
23,0,581,1032,4,"[(608, 265), (776, 265), (776, 314), (608, 314)]",0.96,1,"[(636, 285), (758, 285), (758, 314), (636, 314)]",0.98,3,"[(692, 298), (758, 297), (758, 312), (692, 313)]",0.98,"[1, 5, /, 0, 7, /, 2, 0, 2, 0]",False,None,0

In [56]:
df.loc[('14.jpg', 8), 'y'] = 1

In [57]:
df.xs('15.jpg', level='file')

,n_page,page_height,page_width,n_block,block_vert,block_confidence,n_paragraph,paragraph_vert,paragraph_confidence,n_word,word_vert,word_confidence,text,symbol_search_pos,n_symbol_search_find,y
index,,,,,,,,,,,,,,,,
0,0,581,1032,0,"[(363, 200), (671, 189), (672, 212), (364, 223)]",0.89,0,"[(363, 200), (671, 189), (672, 212), (364, 223)]",0.89,0,"[(363, 200), (451, 197), (452, 220), (364, 223)]",0.99,"[g, a, s, e, o, s, a]",False,None,0
1,0,581,1032,0,"[(363, 200), (671, 189), (672, 212), (364, 223)]",0.89,0,"[(363, 200), (671, 189), (672, 212), (364, 223)]",0.89,1,"[(459, 197), (516, 195), (517, 218), (460, 220)]",0.99,"[C, O, C, A]",False,None,0
2,0,581,1032,0,"[(363, 200), (671, 189), (672, 212), (364, 223)]",0.89,0,"[(363, 200), (671, 189), (672, 212), (364, 223)]",0.89,2,"[(525, 194), (576, 192), (577, 215), (526, 217)]",0.99,"[C, O, L, A]",False,None,0
3,0,581,1032,0,"[(363, 200), (671, 189), (672, 212), (364, 223)]",0.89,0,"[(363, 200), (671, 189), (672, 212), (364, 223)]",0.89,3,"[(609, 192), (642, 191), (643, 213), (610, 214)]",0.82,"[1, ., 7, 5]",False,None,0
4,0,581,1032,0,"[(363, 200), (671, 189), (672, 212), (364, 223)]",0.89,0,"[(363, 200), (671, 189), (672, 212), (364, 223)]",0.89,4,"[(649, 191), (671, 190), (672, 212), (650, 213)]",0.33,"[T, T]",False,None,0
5,0,581,1032,1,"[(450, 250), (635, 247), (636, 309), (451, 312)]",0.69,0,"[(450, 250), (635, 247), (636, 309), (451, 312)]",0.69,0,"[(450, 250), (467, 250), (468, 311), (451, 311)]",0.44,[s],False,None,0
6,0,581,1032,1,"[(450, 250), (635, 247), (636, 309), (451, 312)]",0.69,0,"[(450, 250), (635, 247), (636, 309), (451, 312)]",0.69,1,"[(489, 249), (594, 247), (595, 309), (490, 311)]",0.91,"[1, 2, 2]",False,None,0
7,0,581,1032,1,"[(450, 250), (635, 247), (636, 309), (451, 312)]",0.69,0,"[(450, 250), (635, 247), (636, 309), (451, 312)]",0.69,2,"[(618, 247), (635, 247), (636, 308), (619, 308)]",0.28,[n],False,None,0
8,0,581,1032,2,"[(409, 320), (521, 317), (522, 344), (410, 347)]",0.69,0,"[(409, 320), (519, 318), (519, 333), (409, 335)]",0.79,0,"[(409, 320), (478, 319), (478, 334), (409, 335)]",0.94,"[P, R, E, C, I, O, X, I]",False,None,0
9,0,581,1032,2,"[(409, 320), (521, 317), (522, 344), (410, 347)]",0.69,0,"[(409, 320), (519, 318), (519, 333), (409, 335)]",0.79,1,"[(488, 319), (519, 318), (519, 332), (488, 333)]",0.48,"[5, 7, 0, 1]",False,None,0
10,0,581,1032,2,"[(409, 320), (521, 317), (522, 344), (410, 347)]",0.69,1,"[(432, 334), (521, 331), (521, 343), (432, 346)]",0.60,0,"[(432, 334), (469, 333), (469, 345), (432, 346)]",0.67,"[O, R, I, G, E, N]",False,None,0
11,0,581,1032,2,"[(409, 320), (521, 317), (522, 344), (410, 347)]",0.69,1,"[(432, 334), (521, 331), (521, 343), (432, 346)]",0.60,1,"[(478, 333), (521, 332), (521, 343), (478, 344)]",0.52,"[A, R, G, E, N, T]",False,None,0

In [58]:
df.loc[('15.jpg', 6), 'y'] = 1

In [59]:
df.xs('16.jpg', level='file')

,n_page,page_height,page_width,n_block,block_vert,block_confidence,n_paragraph,paragraph_vert,paragraph_confidence,n_word,word_vert,word_confidence,text,symbol_search_pos,n_symbol_search_find,y
index,,,,,,,,,,,,,,,,
0,0,581,1032,0,"[(258, 143), (639, 131), (640, 156), (259, 168)]",0.98,0,"[(258, 143), (639, 131), (640, 156), (259, 168)]",0.98,0,"[(258, 143), (351, 140), (352, 165), (259, 168)]",0.98,"[g, a, s, e, o, s, a]",False,None,0
1,0,581,1032,0,"[(258, 143), (639, 131), (640, 156), (259, 168)]",0.98,0,"[(258, 143), (639, 131), (640, 156), (259, 168)]",0.98,1,"[(363, 140), (426, 138), (427, 162), (364, 164)]",0.99,"[C, O, C, A]",False,None,0
2,0,581,1032,0,"[(258, 143), (639, 131), (640, 156), (259, 168)]",0.98,0,"[(258, 143), (639, 131), (640, 156), (259, 168)]",0.98,2,"[(438, 137), (497, 135), (498, 160), (439, 162)]",1.00,"[C, O, L, A]",False,None,0
3,0,581,1032,0,"[(258, 143), (639, 131), (640, 156), (259, 168)]",0.98,0,"[(258, 143), (639, 131), (640, 156), (259, 168)]",0.98,3,"[(510, 135), (516, 135), (517, 159), (511, 159)]",0.99,[X],False,None,0
4,0,581,1032,0,"[(258, 143), (639, 131), (640, 156), (259, 168)]",0.98,0,"[(258, 143), (639, 131), (640, 156), (259, 168)]",0.98,4,"[(531, 134), (570, 133), (571, 157), (532, 158)]",0.99,"[1, ., 7, 5]",False,None,0
5,0,581,1032,0,"[(258, 143), (639, 131), (640, 156), (259, 168)]",0.98,0,"[(258, 143), (639, 131), (640, 156), (259, 168)]",0.98,5,"[(582, 132), (594, 132), (595, 157), (583, 157)]",0.96,"[T, I]",False,None,0
6,0,581,1032,0,"[(258, 143), (639, 131), (640, 156), (259, 168)]",0.98,0,"[(258, 143), (639, 131), (640, 156), (259, 168)]",0.98,6,"[(602, 132), (639, 131), (640, 156), (603, 157)]",0.95,"[P, E, T]",False,None,0
7,0,581,1032,1,"[(272, 203), (568, 200), (569, 276), (273, 279)]",0.56,0,"[(272, 203), (568, 200), (569, 276), (273, 279)]",0.56,0,"[(272, 203), (380, 202), (381, 278), (273, 279)]",0.45,"[2, ., s]",False,None,0
8,0,581,1032,1,"[(272, 203), (568, 200), (569, 276), (273, 279)]",0.56,0,"[(272, 203), (568, 200), (569, 276), (273, 279)]",0.56,1,"[(408, 202), (526, 201), (527, 277), (409, 278)]",0.83,"[1, 2, 2]",False,None,0
9,0,581,1032,1,"[(272, 203), (568, 200), (569, 276), (273, 279)]",0.56,0,"[(272, 203), (568, 200), (569, 276), (273, 279)]",0.56,2,"[(547, 201), (568, 201), (569, 276), (548, 276)]",0.07,[»],False,None,0
10,0,581,1032,2,"[(303, 293), (438, 289), (439, 319), (304, 323)]",0.90,0,"[(303, 293), (435, 289), (435, 306), (303, 310)]",0.94,0,"[(303, 293), (362, 291), (362, 308), (303, 310)]",0.99,"[P, R, E, C, I, O]",False,None,0
11,0,581,1032,2,"[(303, 293), (438, 289), (439, 319), (304, 323)]",0.90,0,"[(303, 293), (435, 289), (435, 306), (303, 310)]",0.94,1,"[(369, 291), (386, 291), (386, 307), (369, 307)]",0.84,"[X, I]",False,None,0
12,0,581,1032,2,"[(303, 293), (438, 289), (439, 319), (304, 323)]",0.90,0,"[(303, 293), (435, 289), (435, 306), (303, 310)]",0.94,2,"[(398, 291), (404, 291), (404, 307), (398, 307)]",0.82,[$],True,0,0
13,0,581,1032,2,"[(303, 293), (438, 289), (439, 319), (304, 323)]",0.90,0,"[(303, 293), (435, 289), (435, 306), (303, 310)]",0.94,3,"[(410, 290), (435, 289), (435, 306), (410, 307)]",0.96,"[7, 0, ., 1]",False,None,0
14,0,581,1032,2,"[(303, 293), (438, 289), (439, 319), (304, 323)]",0.90,1,"[(332, 309), (438, 306), (438, 319), (332, 322)]",0.86,0,"[(332, 309), (373, 308), (373, 321), (332, 322)]",0.99,"[O, R, I, G, E, N]",False,None,0
15,0,581,1032,2,"[(303, 293), (438, 289), (439, 319), (304, 323)]",0.90,1,"[(332, 309), (438, 306), (438, 319), (332, 322)]",0.86,1,"[(386, 307), (438, 306), (438, 319), (386, 320)]",0.75,"[A, R, G, E, N, T, I]",False,None,0

In [60]:
df.loc[('16.jpg', 8), 'y'] = 1

In [61]:
df.xs('17.jpg', level='file')

,n_page,page_height,page_width,n_block,block_vert,block_confidence,n_paragraph,paragraph_vert,paragraph_confidence,n_word,word_vert,word_confidence,text,symbol_search_pos,n_symbol_search_find,y
index,,,,,,,,,,,,,,,,
0,0,4032,3024,0,"[(606, 1985), (1821, 2003), (1820, 2059), (605...",0.96,0,"[(606, 1985), (1821, 2003), (1820, 2059), (605...",0.96,0,"[(606, 1985), (829, 1988), (828, 2044), (605, ...",0.99,"[G, A, S, E, O, S, A]",False,None,0
1,0,4032,3024,0,"[(606, 1985), (1821, 2003), (1820, 2059), (605...",0.96,0,"[(606, 1985), (1821, 2003), (1820, 2059), (605...",0.96,1,"[(857, 1989), (969, 1991), (968, 2047), (856, ...",0.99,"[C, O, L, A]",False,None,0
2,0,4032,3024,0,"[(606, 1985), (1821, 2003), (1820, 2059), (605...",0.96,0,"[(606, 1985), (1821, 2003), (1820, 2059), (605...",0.96,2,"[(990, 1991), (1061, 1992), (1060, 2048), (989...",0.99,"[S, I, N]",False,None,0
3,0,4032,3024,0,"[(606, 1985), (1821, 2003), (1820, 2059), (605...",0.96,0,"[(606, 1985), (1821, 2003), (1820, 2059), (605...",0.96,3,"[(1084, 1993), (1261, 1996), (1260, 2051), (10...",0.99,"[A, Z, U, C, A, R]",False,None,0
4,0,4032,3024,0,"[(606, 1985), (1821, 2003), (1820, 2059), (605...",0.96,0,"[(606, 1985), (1821, 2003), (1820, 2059), (605...",0.96,4,"[(1279, 1995), (1403, 1997), (1402, 2053), (12...",0.99,"[C, O, C, A]",False,None,0
5,0,4032,3024,0,"[(606, 1985), (1821, 2003), (1820, 2059), (605...",0.96,0,"[(606, 1985), (1821, 2003), (1820, 2059), (605...",0.96,5,"[(1422, 1997), (1535, 1999), (1534, 2055), (14...",1.00,"[C, O, L, A]",False,None,0
6,0,4032,3024,0,"[(606, 1985), (1821, 2003), (1820, 2059), (605...",0.96,0,"[(606, 1985), (1821, 2003), (1820, 2059), (605...",0.96,6,"[(1557, 2000), (1643, 2001), (1642, 2056), (15...",0.99,"[P, E, T]",False,None,0
7,0,4032,3024,0,"[(606, 1985), (1821, 2003), (1820, 2059), (605...",0.96,0,"[(606, 1985), (1821, 2003), (1820, 2059), (605...",0.96,7,"[(1658, 2001), (1679, 2001), (1678, 2056), (16...",0.94,[X],False,None,0
8,0,4032,3024,0,"[(606, 1985), (1821, 2003), (1820, 2059), (605...",0.96,0,"[(606, 1985), (1821, 2003), (1820, 2059), (605...",0.96,8,"[(1698, 2002), (1755, 2003), (1754, 2058), (16...",0.73,"[2, ., 5]",False,None,0
9,0,4032,3024,0,"[(606, 1985), (1821, 2003), (1820, 2059), (605...",0.96,0,"[(606, 1985), (1821, 2003), (1820, 2059), (605...",0.96,9,"[(1774, 2003), (1821, 2004), (1820, 2060), (17...",0.82,"[L, T]",False,None,0
10,0,4032,3024,1,"[(1639, 2063), (1790, 2067), (1786, 2202), (16...",0.99,0,"[(1639, 2063), (1790, 2067), (1786, 2202), (16...",0.99,0,"[(1639, 2063), (1790, 2067), (1786, 2202), (16...",0.99,"[0, 0]",False,None,0
11,0,4032,3024,2,"[(779, 2198), (838, 2196), (842, 2295), (783, ...",0.95,0,"[(779, 2198), (838, 2196), (842, 2295), (783, ...",0.95,0,"[(779, 2198), (838, 2196), (842, 2295), (783, ...",0.95,[$],True,0,0
12,0,4032,3024,3,"[(953, 2028), (1653, 2017), (1660, 2433), (960...",0.99,0,"[(953, 2028), (1653, 2017), (1660, 2433), (960...",0.99,0,"[(953, 2028), (1653, 2017), (1660, 2433), (960...",0.99,"[1, 4, 3]",False,None,0
13,0,4032,3024,4,"[(1486, 2479), (1711, 2481), (1710, 2599), (14...",0.95,0,"[(1486, 2479), (1711, 2481), (1710, 2599), (14...",0.95,0,"[(1486, 2479), (1615, 2480), (1615, 2522), (14...",0.99,"[P, r, e, c, i, o]",False,None,0
14,0,4032,3024,4,"[(1486, 2479), (1711, 2481), (1710, 2599), (14...",0.95,0,"[(1486, 2479), (1711, 2481), (1710, 2599), (14...",0.95,1,"[(1634, 2481), (1651, 2481), (1651, 2522), (16...",1.00,[x],False,None,0
15,0,4032,3024,4,"[(1486, 2479), (1711, 2481), (1710, 2599), (14...",0.95,0,"[(1486, 2479), (1711, 2481), (1710, 2599), (14...",0.95,2,"[(1683, 2481), (1711, 2481), (1711, 2523), (16...",0.96,"[1, L]",False,None,0
16,0,4032,3024,4,"[(1486, 2479), (1711, 2481), (1710, 2599), (14...",0.95,0,"[(1486, 2479), (1711, 2481), (1710, 2599), (14...",0.95,3,"[(1488, 2534), (1505, 2534), (1505, 2597), (14...",0.75,[$],True,0,0
17,0,4032,3024,4,"[(1486, 2479), (1711, 2481), (1710, 2599), (14...",0.95,0,"[(1486, 2479), (1711, 2481), (1710, 2599), (14...",0.95,4,"[(1526, 2534), (1663, 2534), (1663, 2597), (15...",0.92,"[5, 7, 2, 0]",False,None,0
18,0,4032,3024,5,"[(1804, 2509), (1927, 2510), (1927, 2550), (18...",0.99,0,"[(1804, 2509), (1927, 2510), (1927, 2550), (18...",0.99,0,"[(1804, 2509), (1927, 2510), (1927, 2550), (18...",0.99,"[1, 4, ., 0, 2]",False,None,0
19,0,4032,3024,6,"[(640, 2579), (1391, 2572), (1391, 2621), (640...",0.58,0,"[(640, 2579), (1391, 2572), (1391, 2621), (640...",0.58,0,"[(640, 2579), (1208, 2574), (1208, 2623), (640...",0.52,"[7, 7, 0, 0, R, O, S, O, G, R, O, G, O, I, G, ...",False,None,0
20,0,4032,3024,6,"[(640, 2579), (1391, 2572), (1391, 2621), (640...",0.58,0,"[(640, 2579), (1391, 2572), (1391, 2621), (640...",0.58,1,"[(1247, 2573), (1391, 2572), (1391, 2621), (12...",0.71,"[A, r, g, e, n, t, i, n, a]",False,None,0
21,0,4032,3024,7,"[(728, 3278), (616, 3605), (427, 3541), (539, ...",0.60,0,"[(728, 3278), (616, 3605), (427, 3541), (539, ...",0.60,0,"[(728, 3278), (616, 3605), (427, 3541), (539, ...",0.60,"[e, e]",False,None,0
22,0,4032,3024,8,"[(12, 3620), (99, 3621), (95, 3840), (8, 3839)]",1.00,0,"[(12, 3620), (99, 3621), (95, 3840), (8, 3839)]",1.00,0,"[(12, 3620), (99, 3621), (95, 3840), (8, 3839)]",1.00,[M],False,None,0
23,0,4032,3024,9,"[(269, 3712), (442, 3536), (550, 3642), (376, ...",0.79,0,"[(269, 3712), (442, 3536), (550, 3642), (376, ...",0.79,0,"[(269, 3712), (442, 3536), (550, 3642), (376, ...",0.79,"[o, r]",False,None,0

In [62]:
df.loc[('17.jpg', 12), 'y'] = 1

In [63]:
df.xs('18.jpg', level='file')

,n_page,page_height,page_width,n_block,block_vert,block_confidence,n_paragraph,paragraph_vert,paragraph_confidence,n_word,word_vert,word_confidence,text,symbol_search_pos,n_symbol_search_find,y
index,,,,,,,,,,,,,,,,
0,0,4032,3024,0,"[(794, 1815), (2096, 1820), (2096, 1882), (794...",0.97,0,"[(794, 1815), (2096, 1820), (2096, 1882), (794...",0.97,0,"[(794, 1815), (1053, 1816), (1053, 1878), (794...",0.99,"[G, A, S, E, O, S, A]",False,None,0
1,0,4032,3024,0,"[(794, 1815), (2096, 1820), (2096, 1882), (794...",0.97,0,"[(794, 1815), (2096, 1820), (2096, 1882), (794...",0.97,1,"[(1073, 1817), (1205, 1818), (1205, 1879), (10...",0.97,"[C, O, L, A]",False,None,0
2,0,4032,3024,0,"[(794, 1815), (2096, 1820), (2096, 1882), (794...",0.97,0,"[(794, 1815), (2096, 1820), (2096, 1882), (794...",0.97,2,"[(1232, 1817), (1383, 1818), (1383, 1880), (12...",0.99,"[L, I, G, H, T]",False,None,0
3,0,4032,3024,0,"[(794, 1815), (2096, 1820), (2096, 1882), (794...",0.97,0,"[(794, 1815), (2096, 1820), (2096, 1882), (794...",0.97,3,"[(1400, 1818), (1552, 1819), (1552, 1880), (14...",0.99,"[C, O, C, A]",False,None,0
4,0,4032,3024,0,"[(794, 1815), (2096, 1820), (2096, 1882), (794...",0.97,0,"[(794, 1815), (2096, 1820), (2096, 1882), (794...",0.97,4,"[(1565, 1819), (1716, 1820), (1716, 1881), (15...",1.00,"[C, O, L, A]",False,None,0
5,0,4032,3024,0,"[(794, 1815), (2096, 1820), (2096, 1882), (794...",0.97,0,"[(794, 1815), (2096, 1820), (2096, 1882), (794...",0.97,5,"[(1723, 1819), (1838, 1819), (1838, 1880), (17...",0.99,"[P, E, T]",False,None,0
6,0,4032,3024,0,"[(794, 1815), (2096, 1820), (2096, 1882), (794...",0.97,0,"[(794, 1815), (2096, 1820), (2096, 1882), (794...",0.97,6,"[(1859, 1820), (1876, 1820), (1876, 1881), (18...",0.98,[X],False,None,0
7,0,4032,3024,0,"[(794, 1815), (2096, 1820), (2096, 1882), (794...",0.97,0,"[(794, 1815), (2096, 1820), (2096, 1882), (794...",0.97,7,"[(1916, 1820), (2002, 1820), (2002, 1881), (19...",0.95,"[1, ., 7, 5]",False,None,0
8,0,4032,3024,0,"[(794, 1815), (2096, 1820), (2096, 1882), (794...",0.97,0,"[(794, 1815), (2096, 1820), (2096, 1882), (794...",0.97,8,"[(2027, 1820), (2096, 1820), (2096, 1881), (20...",0.80,"[L, T]",False,None,0
9,0,4032,3024,1,"[(2016, 1935), (2222, 1934), (2223, 2078), (20...",0.92,0,"[(2016, 1935), (2222, 1934), (2223, 2078), (20...",0.92,0,"[(2016, 1935), (2222, 1934), (2223, 2078), (20...",0.92,"[0, 0]",False,None,0
10,0,4032,3024,2,"[(1024, 1856), (2173, 1880), (2162, 2391), (10...",0.99,0,"[(1024, 1856), (2173, 1880), (2162, 2391), (10...",0.99,0,"[(1024, 1856), (2173, 1880), (2162, 2391), (10...",0.99,"[1, 1, 4]",False,None,0
11,0,4032,3024,3,"[(1894, 2415), (2213, 2420), (2211, 2534), (18...",0.89,0,"[(1895, 2415), (2213, 2427), (2211, 2485), (18...",0.87,0,"[(1895, 2415), (2047, 2421), (2045, 2479), (18...",0.99,"[P, r, e, c, i, o]",False,None,0
12,0,4032,3024,3,"[(1894, 2415), (2213, 2420), (2211, 2534), (18...",0.89,0,"[(1895, 2415), (2213, 2427), (2211, 2485), (18...",0.87,1,"[(2085, 2423), (2101, 2424), (2099, 2481), (20...",0.96,[x],False,None,0
13,0,4032,3024,3,"[(1894, 2415), (2213, 2420), (2211, 2534), (18...",0.89,0,"[(1895, 2415), (2213, 2427), (2211, 2485), (18...",0.87,2,"[(2141, 2425), (2184, 2427), (2182, 2484), (21...",0.63,"[T, L]",False,None,0
14,0,4032,3024,3,"[(1894, 2415), (2213, 2420), (2211, 2534), (18...",0.89,0,"[(1895, 2415), (2213, 2427), (2211, 2485), (18...",0.87,3,"[(2197, 2427), (2213, 2428), (2211, 2485), (21...",0.57,[.],False,None,0
15,0,4032,3024,3,"[(1894, 2415), (2213, 2420), (2211, 2534), (18...",0.89,1,"[(2067, 2494), (2116, 2494), (2116, 2532), (20...",0.99,0,"[(2067, 2494), (2116, 2494), (2116, 2532), (20...",0.99,"[1, 4]",False,None,0
16,0,4032,3024,4,"[(2254, 2458), (2441, 2466), (2438, 2528), (22...",0.99,0,"[(2254, 2458), (2441, 2466), (2438, 2528), (22...",0.99,0,"[(2254, 2458), (2441, 2466), (2438, 2528), (22...",0.99,"[0, 9, ., 0, 3]",False,None,0
17,0,4032,3024,5,"[(906, 2511), (1757, 2531), (1755, 2589), (905...",0.99,0,"[(906, 2511), (1757, 2531), (1755, 2589), (905...",0.99,0,"[(906, 2511), (1341, 2521), (1340, 2579), (905...",0.99,"[7, 7, 9, 0, 8, 9, 5, 0, 1, 2, 4, 4, 0]",False,None,0
18,0,4032,3024,5,"[(906, 2511), (1757, 2531), (1755, 2589), (905...",0.99,0,"[(906, 2511), (1757, 2531), (1755, 2589), (905...",0.99,1,"[(1395, 2523), (1553, 2527), (1552, 2585), (13...",0.99,"[O, R, I, G, E, N]",False,None,0
19,0,4032,3024,5,"[(906, 2511), (1757, 2531), (1755, 2589), (905...",0.99,0,"[(906, 2511), (1757, 2531), (1755, 2589), (905...",0.99,2,"[(1561, 2527), (1577, 2527), (1576, 2584), (15...",0.99,[:],False,None,0
20,0,4032,3024,5,"[(906, 2511), (1757, 2531), (1755, 2589), (905...",0.99,0,"[(906, 2511), (1757, 2531), (1755, 2589), (905...",0.99,3,"[(1584, 2527), (1757, 2531), (1756, 2589), (15...",0.99,"[A, r, g, e, n, t, i, n, a]",False,None,0
21,0,4032,3024,6,"[(1899, 2495), (2114, 2485), (2118, 2567), (19...",0.54,0,"[(1899, 2495), (2114, 2485), (2118, 2567), (19...",0.54,0,"[(1899, 2495), (1922, 2494), (1926, 2577), (19...",0.12,[s],False,None,0
22,0,4032,3024,6,"[(1899, 2495), (2114, 2485), (2118, 2567), (19...",0.54,0,"[(1899, 2495), (2114, 2485), (2118, 2567), (19...",0.54,1,"[(1943, 2493), (2114, 2485), (2118, 2568), (19...",0.65,"[6, 5, 1, 4]",False,None,0

In [64]:
df.loc[('18.jpg', 10), 'y'] = 1

In [65]:
df.xs('19.jpg', level='file')

,n_page,page_height,page_width,n_block,block_vert,block_confidence,n_paragraph,paragraph_vert,paragraph_confidence,n_word,word_vert,word_confidence,text,symbol_search_pos,n_symbol_search_find,y
index,,,,,,,,,,,,,,,,
0,0,4032,3024,0,"[(1237, 2032), (2942, 1979), (2944, 2044), (12...",0.99,0,"[(1237, 2032), (2942, 1979), (2944, 2044), (12...",0.99,0,"[(1237, 2033), (1546, 2023), (1548, 2086), (12...",0.99,"[G, A, S, E, O, S, A]",False,None,0
1,0,4032,3024,0,"[(1237, 2032), (2942, 1979), (2944, 2044), (12...",0.99,0,"[(1237, 2032), (2942, 1979), (2944, 2044), (12...",0.99,1,"[(1569, 2023), (1748, 2017), (1750, 2080), (15...",0.99,"[C, O, L, A]",False,None,0
2,0,4032,3024,0,"[(1237, 2032), (2942, 1979), (2944, 2044), (12...",0.99,0,"[(1237, 2032), (2942, 1979), (2944, 2044), (12...",0.99,2,"[(1773, 2016), (2076, 2007), (2078, 2071), (17...",0.99,"[R, E, G, U, L, A, R]",False,None,0
3,0,4032,3024,0,"[(1237, 2032), (2942, 1979), (2944, 2044), (12...",0.99,0,"[(1237, 2032), (2942, 1979), (2944, 2044), (12...",0.99,3,"[(2101, 2006), (2284, 2000), (2286, 2063), (21...",0.99,"[C, O, C, A]",False,None,0
4,0,4032,3024,0,"[(1237, 2032), (2942, 1979), (2944, 2044), (12...",0.99,0,"[(1237, 2032), (2942, 1979), (2944, 2044), (12...",0.99,4,"[(2309, 2000), (2486, 1995), (2488, 2058), (23...",1.00,"[C, O, L, A]",False,None,0
5,0,4032,3024,0,"[(1237, 2032), (2942, 1979), (2944, 2044), (12...",0.99,0,"[(1237, 2032), (2942, 1979), (2944, 2044), (12...",0.99,5,"[(2513, 1993), (2634, 1989), (2636, 2053), (25...",0.99,"[P, E, T]",False,None,0
6,0,4032,3024,0,"[(1237, 2032), (2942, 1979), (2944, 2044), (12...",0.99,0,"[(1237, 2032), (2942, 1979), (2944, 2044), (12...",0.99,6,"[(2651, 1989), (2692, 1988), (2694, 2051), (26...",0.98,[X],False,None,0
7,0,4032,3024,0,"[(1237, 2032), (2942, 1979), (2944, 2044), (12...",0.99,0,"[(1237, 2032), (2942, 1979), (2944, 2044), (12...",0.99,7,"[(2715, 1987), (2844, 1983), (2846, 2047), (27...",0.99,"[2, ., 2, 5]",False,None,0
8,0,4032,3024,0,"[(1237, 2032), (2942, 1979), (2944, 2044), (12...",0.99,0,"[(1237, 2032), (2942, 1979), (2944, 2044), (12...",0.99,8,"[(2871, 1982), (2933, 1980), (2935, 2044), (28...",0.99,"[L, T]",False,None,0
9,0,4032,3024,0,"[(1237, 2032), (2942, 1979), (2944, 2044), (12...",0.99,0,"[(1237, 2032), (2942, 1979), (2944, 2044), (12...",0.99,9,"[(2930, 1981), (2942, 1981), (2944, 2044), (29...",0.99,[.],False,None,0
10,0,4032,3024,1,"[(92, 2071), (922, 2058), (924, 2214), (94, 22...",0.94,0,"[(92, 2071), (922, 2058), (924, 2214), (94, 22...",0.94,0,"[(92, 2071), (804, 2060), (806, 2216), (94, 22...",0.99,"[P, R, O, M, O]",False,None,0
11,0,4032,3024,1,"[(92, 2071), (922, 2058), (924, 2214), (94, 22...",0.94,0,"[(92, 2071), (922, 2058), (924, 2214), (94, 22...",0.94,1,"[(878, 2060), (922, 2059), (924, 2214), (880, ...",0.71,[!],False,None,0
12,0,4032,3024,2,"[(1049, 2150), (1833, 2125), (1834, 2169), (10...",0.99,0,"[(1049, 2150), (1833, 2125), (1834, 2169), (10...",0.99,0,"[(1049, 2150), (1286, 2142), (1287, 2186), (10...",0.99,"[L, L, E, V, A, N, D, O]",False,None,0
13,0,4032,3024,2,"[(1049, 2150), (1833, 2125), (1834, 2169), (10...",0.99,0,"[(1049, 2150), (1833, 2125), (1834, 2169), (10...",0.99,1,"[(1315, 2142), (1327, 2142), (1328, 2185), (13...",0.99,[2],False,None,0
14,0,4032,3024,2,"[(1049, 2150), (1833, 2125), (1834, 2169), (10...",0.99,0,"[(1049, 2150), (1833, 2125), (1834, 2169), (10...",0.99,2,"[(1351, 2141), (1636, 2132), (1637, 2175), (13...",0.99,"[P, R, O, D, U, C, T, O, S]",False,None,0
15,0,4032,3024,2,"[(1049, 2150), (1833, 2125), (1834, 2169), (10...",0.99,0,"[(1049, 2150), (1833, 2125), (1834, 2169), (10...",0.99,3,"[(1649, 2131), (1833, 2125), (1834, 2169), (16...",0.99,"[I, G, U, A, L, E, S]",False,None,0
16,0,4032,3024,3,"[(1056, 2151), (3014, 2121), (3019, 2464), (10...",0.84,0,"[(1056, 2151), (3014, 2121), (3019, 2464), (10...",0.84,0,"[(1056, 2151), (1440, 2145), (1445, 2489), (10...",0.99,"[5, 0]",False,None,0
17,0,4032,3024,3,"[(1056, 2151), (3014, 2121), (3019, 2464), (10...",0.84,0,"[(1056, 2151), (3014, 2121), (3019, 2464), (10...",0.84,1,"[(1639, 2142), (1870, 2138), (1875, 2481), (16...",0.99,[%],False,None,0
18,0,4032,3024,3,"[(1056, 2151), (3014, 2121), (3019, 2464), (10...",0.84,0,"[(1056, 2151), (3014, 2121), (3019, 2464), (10...",0.84,2,"[(1985, 2137), (2087, 2135), (2092, 2478), (19...",0.92,[$],True,0,0
19,0,4032,3024,3,"[(1056, 2151), (3014, 2121), (3019, 2464), (10...",0.84,0,"[(1056, 2151), (3014, 2121), (3019, 2464), (10...",0.84,3,"[(2156, 2134), (3014, 2121), (3019, 2465), (21...",0.71,"[1, 0, 7, 2]",False,None,0
20,0,4032,3024,4,"[(533, 2327), (639, 2338), (634, 2388), (528, ...",0.99,0,"[(533, 2327), (639, 2338), (634, 2388), (528, ...",0.99,0,"[(533, 2327), (639, 2338), (634, 2388), (528, ...",0.99,"[P, A, R, A]",False,None,0
21,0,4032,3024,5,"[(317, 2417), (493, 2299), (540, 2368), (364, ...",0.99,0,"[(317, 2417), (493, 2299), (540, 2368), (364, ...",0.99,0,"[(317, 2417), (493, 2299), (540, 2368), (364, ...",0.99,"[A, C, C, I, O, N, E, S]",False,None,0
22,0,4032,3024,6,"[(1528, 2439), (1808, 2437), (1808, 2475), (15...",0.92,0,"[(1528, 2439), (1808, 2437), (1808, 2475), (15...",0.92,0,"[(1528, 2439), (1808, 2437), (1808, 2475), (15...",0.92,"[D, E, S, C, U, E, N, T, O]",False,None,0
23,0,4032,3024,7,"[(1203, 2513), (1684, 2502), (1685, 2548), (12...",0.97,0,"[(1203, 2513), (1684, 2502), (1685, 2548), (12...",0.97,0,"[(1203, 2513), (1266, 2512), (1267, 2558), (12...",0.99,"[E, N]",False,None,0
24,0,4032,3024,7,"[(1203, 2513), (1684, 2502), (1685, 2548), (12...",0.97,0,"[(1203, 2513), (1684, 2502), (1685, 2548), (12...",0.97,1,"[(1287, 2511), (1350, 2510), (1351, 2556), (12...",0.99,"[L, A]",False,None,0
25,0,4032,3024,7,"[(1203, 2513), (1684, 2502), (1685, 2548), (12...",0.97,0,"[(1203, 2513), (1684, 2502), (1685, 2548), (12...",0.97,2,"[(1369, 2509), (1468, 2507), (1469, 2553), (13...",0.93,"[2, D, A]",False,None,0
26,0,4032,3024,7,"[(1203, 2513), (1684, 2502), (1685, 2548), (12...",0.97,0,"[(1203, 2513), (1684, 2502), (1685, 2548), (12...",0.97,3,"[(1485, 2507), (1684, 2502), (1685, 2547), (14...",0.99,"[U, N, I, D, A, D]",False,None,0
27,0,4032,3024,8,"[(2323, 2516), (2525, 2509), (2526, 2540), (23...",0.92,0,"[(2323, 2516), (2525, 2509), (2526, 2540), (23...",0.92,0,"[(2323, 2517), (2408, 2514), (2409, 2544), (23...",0.98,"[P, R, E, C, I, O]",False,None,0
28,0,4032,3024,8,"[(2323, 2516), (2525, 2509), (2526, 2540), (23...",0.92,0,"[(2323, 2516), (2525, 2509), (2526, 2540), (23...",0.92,1,"[(2420, 2513), (2525, 2509), (2526, 2539), (24...",0.86,"[N, O, R, M, A, L]",False,None,0
29,0,4032,3024,9,"[(388, 2475), (677, 2398), (721, 2565), (432, ...",0.99,0,"[(388, 2475), (677, 2398), (721, 2565), (432, ...",0.99,0,"[(388, 2475), (673, 2401), (694, 2482), (409, ...",0.99,"[P, A, G, A, R]",False,None,0
30,0,4032,3024,9,"[(388, 2475), (677, 2398), (721, 2565), (432, ...",0.99,0,"[(388, 2475), (677, 2398), (721, 2565), (432, ...",0.99,1,"[(427, 2556), (699, 2482), (721, 2563), (449, ...",0.99,"[M, E, N, O, S]",False,None,0
31,0,4032,3024,10,"[(1950, 2539), (2065, 2539), (2065, 2640), (19...",0.94,0,"[(1950, 2539), (2065, 2539), (2065, 2640), (19...",0.94,0,"[(1954, 2539), (2061, 2539), (2061, 2585), (19...",0.93,"[M, á, x]",False,None,0
32,0,4032,3024,10,"[(1950, 2539), (2065, 2539), (2065, 2640), (19...",0.94,0,"[(1950, 2539), (2065, 2539), (2065, 2640), (19...",0.94,1,"[(1950, 2600), (2006, 2600), (2006, 2640), (19...",0.99,"[1, 6]",False,None,0
33,0,4032,3024,10,"[(1950, 2539), (2065, 2539), (2065, 2640), (19...",0.94,0,"[(1950, 2539), (2065, 2539), (2065, 2640), (19...",0.94,2,"[(2024, 2600), (2051, 2600), (2051, 2640), (20...",0.94,[u],False,None,0
34,0,4032,3024,10,"[(1950, 2539), (2065, 2539), (2065, 2640), (19...",0.94,0,"[(1950, 2539), (2065, 2539), (2065, 2640), (19...",0.94,3,"[(2055, 2600), (2065, 2600), (2065, 2640), (20...",0.89,[.],False,None,0
35,0,4032,3024,11,"[(2280, 2547), (2546, 2544), (2547, 2647), (22...",0.75,0,"[(2280, 2547), (2546, 2544), (2547, 2647), (22...",0.75,0,"[(2280, 2547), (2303, 2547), (2304, 2650), (22...",0.35,[s],False,None,0
36,0,4032,3024,11,"[(2280, 2547), (2546, 2544), (2547, 2647), (22...",0.75,0,"[(2280, 2547), (2546, 2544), (2547, 2647), (22...",0.75,1,"[(2323, 2547), (2546, 2544), (2547, 2647), (23...",0.89,"[1, 4, 3]",False,None,0
37,0,4032,3024,12,"[(2874, 2532), (2968, 2529), (2971, 2629), (28...",0.08,0,"[(2874, 2532), (2968, 2529), (2971, 2629), (28...",0.08,0,"[(2874, 2532), (2968, 2529), (2971, 2629), (28...",0.08,"[1, 1]",False,None,0
38,0,4032,3024,13,"[(1223, 2605), (1663, 2596), (1664, 2647), (12...",0.99,0,"[(1223, 2605), (1663, 2596), (1664, 2647), (12...",0.99,0,"[(1223, 2605), (1301, 2603), (1302, 2654), (12...",0.99,"[D, e, l]",False,None,0
39,0,4032,3024,13,"[(1223, 2605), (1663, 2596), (1664, 2647), (12...",0.99,0,"[(1223, 2605), (1663, 2596), (1664, 2647), (12...",0.99,1,"[(1320, 2603), (1454, 2600), (1455, 2651), (13...",0.99,"[3, 0, /, 0, 6]",False,None,0
40,0,4032,3024,13,"[(1223, 2605), (1663, 2596), (1664, 2647), (12...",0.99,0,"[(1223, 2605), (1663, 2596), (1664, 2647), (12...",0.99,2,"[(1471, 2600), (1512, 2599), (1513, 2649), (14...",0.99,"[a, l]",False,None,0
41,0,4032,3024,13,"[(1223, 2605), (1663, 2596), (1664, 2647), (12...",0.99,0,"[(1223, 2605), (1663, 2596), (1664, 2647), (12...",0.99,3,"[(1528, 2599), (1663, 2596), (1664, 2646), (15...",0.98,"[0, 6, /, 0, 7]",False,None,0
42,0,4032,3024,14,"[(550, 2625), (570, 2621), (583, 2691), (563, ...",0.07,0,"[(550, 2625), (570, 2621), (583, 2691), (563, ...",0.07,0,"[(550, 2625), (570, 2621), (583, 2691), (563, ...",0.07,[<],False,None,0
43,0,4032,3024,15,"[(2683, 2626), (3013, 2616), (3014, 2652), (26...",0.80,0,"[(2683, 2626), (3013, 2616), (3014, 2652), (26...",0.80,0,"[(2683, 2626), (2890, 2620), (2891, 2656), (26...",0.73,"[7, ., 7, 9, 0, 8, 9, 5]",False,None,0
44,0,4032,3024,15,"[(2683, 2626), (3013, 2616), (3014, 2652), (26...",0.80,0,"[(2683, 2626), (3013, 2616), (3014, 2652), (26...",0.80,1,"[(2905, 2620), (2914, 2620), (2915, 2655), (29...",0.93,"[""]",False,None,0
45,0,4032,3024,15,"[(2683, 2626), (3013, 2616), (3014, 2652), (26...",0.80,0,"[(2683, 2626), (3013, 2616), (3014, 2652), (26...",0.80,2,"[(2925, 2619), (3013, 2616), (3014, 2652), (29...",0.97,"[0, 0, 0]",False,None,0
46,0,4032,3024,16,"[(2200, 2678), (2539, 2668), (2540, 2704), (22...",0.82,0,"[(2200, 2678), (2539, 2668), (2540, 2704), (22...",0.82,0,"[(2200, 2678), (2331, 2674), (2332, 2710), (22...",0.99,"[P, R, E, C, I, O]",False,None,0
47,0,4032,3024,16,"[(2200, 2678), (2539, 2668), (2540, 2704), (22...",0.82,0,"[(2200, 2678), (2539, 2668), (2540, 2704), (22...",0.82,1,"[(2343, 2674), (2390, 2673), (2391, 2708), (23...",0.92,"[X, 1]",False,None,0
48,0,4032,3024,16,"[(2200, 2678), (2539, 2668), (2540, 2704), (22...",0.82,0,"[(2200, 2678), (2539, 2668), (2540, 2704), (22...",0.82,2,"[(2406, 2672), (2421, 2672), (2422, 2707), (24...",0.47,[L],False,None,0
49,0,4032,3024,16,"[(2200, 2678), (2539, 2668), (2540, 2704), (22...",0.82,0,"[(2200, 2678), (2539, 2668), (2540, 2704), (22...",0.82,3,"[(2425, 2672), (2441, 2672), (2442, 2707), (24...",0.16,[:],False,None,0
50,0,4032,3024,16,"[(2200, 2678), (2539, 2668), (2540, 2704), (22...",0.82,0,"[(2200, 2678), (2539, 2668), (2540, 2704), (22...",0.82,4,"[(2453, 2671), (2539, 2669), (2540, 2705), (24...",0.77,"[6, 3, ,, 5, 5]",False,None,0
51,0,4032,3024,17,"[(693, 2687), (754, 2633), (791, 2674), (729, ...",0.81,0,"[(693, 2687), (754, 2633), (791, 2674), (729, ...",0.81,0,"[(693, 2687), (754, 2633), (791, 2674), (729, ...",0.81,"[M, Á, S]",False,None,0
52,0,4032,3024,18,"[(510, 2713), (710, 2696), (716, 2762), (516, ...",0.90,0,"[(510, 2713), (710, 2696), (716, 2762), (516, ...",0.90,0,"[(510, 2713), (710, 2696), (716, 2762), (516, ...",0.90,"[A, H, O, R, R, A, R]",False,None,0
53,0,4032,3024,19,"[(2616, 3195), (2738, 3298), (2657, 3395), (25...",0.60,0,"[(2616, 3195), (2738, 3298), (2657, 3395), (25...",0.60,0,"[(2616, 3195), (2738, 3298), (2657, 3395), (25...",0.60,"[e, c, d]",False,None,0

In [69]:
df = df.drop('19.jpg', level='file')

In [68]:
df.xs('20.jpg', level='file')

,n_page,page_height,page_width,n_block,block_vert,block_confidence,n_paragraph,paragraph_vert,paragraph_confidence,n_word,word_vert,word_confidence,text,symbol_search_pos,n_symbol_search_find,y
index,,,,,,,,,,,,,,,,
0,0,4032,3024,0,"[(1237, 2032), (2942, 1979), (2944, 2044), (12...",0.99,0,"[(1237, 2032), (2942, 1979), (2944, 2044), (12...",0.99,0,"[(1237, 2033), (1546, 2023), (1548, 2086), (12...",0.99,"[G, A, S, E, O, S, A]",False,None,0
1,0,4032,3024,0,"[(1237, 2032), (2942, 1979), (2944, 2044), (12...",0.99,0,"[(1237, 2032), (2942, 1979), (2944, 2044), (12...",0.99,1,"[(1569, 2023), (1748, 2017), (1750, 2080), (15...",0.99,"[C, O, L, A]",False,None,0
2,0,4032,3024,0,"[(1237, 2032), (2942, 1979), (2944, 2044), (12...",0.99,0,"[(1237, 2032), (2942, 1979), (2944, 2044), (12...",0.99,2,"[(1773, 2016), (2076, 2007), (2078, 2071), (17...",0.99,"[R, E, G, U, L, A, R]",False,None,0
3,0,4032,3024,0,"[(1237, 2032), (2942, 1979), (2944, 2044), (12...",0.99,0,"[(1237, 2032), (2942, 1979), (2944, 2044), (12...",0.99,3,"[(2101, 2006), (2284, 2000), (2286, 2063), (21...",0.99,"[C, O, C, A]",False,None,0
4,0,4032,3024,0,"[(1237, 2032), (2942, 1979), (2944, 2044), (12...",0.99,0,"[(1237, 2032), (2942, 1979), (2944, 2044), (12...",0.99,4,"[(2309, 2000), (2486, 1995), (2488, 2058), (23...",1.00,"[C, O, L, A]",False,None,0
5,0,4032,3024,0,"[(1237, 2032), (2942, 1979), (2944, 2044), (12...",0.99,0,"[(1237, 2032), (2942, 1979), (2944, 2044), (12...",0.99,5,"[(2513, 1993), (2634, 1989), (2636, 2053), (25...",0.99,"[P, E, T]",False,None,0
6,0,4032,3024,0,"[(1237, 2032), (2942, 1979), (2944, 2044), (12...",0.99,0,"[(1237, 2032), (2942, 1979), (2944, 2044), (12...",0.99,6,"[(2651, 1989), (2692, 1988), (2694, 2051), (26...",0.98,[X],False,None,0
7,0,4032,3024,0,"[(1237, 2032), (2942, 1979), (2944, 2044), (12...",0.99,0,"[(1237, 2032), (2942, 1979), (2944, 2044), (12...",0.99,7,"[(2715, 1987), (2844, 1983), (2846, 2047), (27...",0.99,"[2, ., 2, 5]",False,None,0
8,0,4032,3024,0,"[(1237, 2032), (2942, 1979), (2944, 2044), (12...",0.99,0,"[(1237, 2032), (2942, 1979), (2944, 2044), (12...",0.99,8,"[(2871, 1982), (2933, 1980), (2935, 2044), (28...",0.99,"[L, T]",False,None,0
9,0,4032,3024,0,"[(1237, 2032), (2942, 1979), (2944, 2044), (12...",0.99,0,"[(1237, 2032), (2942, 1979), (2944, 2044), (12...",0.99,9,"[(2930, 1981), (2942, 1981), (2944, 2044), (29...",0.99,[.],False,None,0
10,0,4032,3024,1,"[(92, 2071), (922, 2058), (924, 2214), (94, 22...",0.94,0,"[(92, 2071), (922, 2058), (924, 2214), (94, 22...",0.94,0,"[(92, 2071), (804, 2060), (806, 2216), (94, 22...",0.99,"[P, R, O, M, O]",False,None,0
11,0,4032,3024,1,"[(92, 2071), (922, 2058), (924, 2214), (94, 22...",0.94,0,"[(92, 2071), (922, 2058), (924, 2214), (94, 22...",0.94,1,"[(878, 2060), (922, 2059), (924, 2214), (880, ...",0.71,[!],False,None,0
12,0,4032,3024,2,"[(1049, 2150), (1833, 2125), (1834, 2169), (10...",0.99,0,"[(1049, 2150), (1833, 2125), (1834, 2169), (10...",0.99,0,"[(1049, 2150), (1286, 2142), (1287, 2186), (10...",0.99,"[L, L, E, V, A, N, D, O]",False,None,0
13,0,4032,3024,2,"[(1049, 2150), (1833, 2125), (1834, 2169), (10...",0.99,0,"[(1049, 2150), (1833, 2125), (1834, 2169), (10...",0.99,1,"[(1315, 2142), (1327, 2142), (1328, 2185), (13...",0.99,[2],False,None,0
14,0,4032,3024,2,"[(1049, 2150), (1833, 2125), (1834, 2169), (10...",0.99,0,"[(1049, 2150), (1833, 2125), (1834, 2169), (10...",0.99,2,"[(1351, 2141), (1636, 2132), (1637, 2175), (13...",0.99,"[P, R, O, D, U, C, T, O, S]",False,None,0
15,0,4032,3024,2,"[(1049, 2150), (1833, 2125), (1834, 2169), (10...",0.99,0,"[(1049, 2150), (1833, 2125), (1834, 2169), (10...",0.99,3,"[(1649, 2131), (1833, 2125), (1834, 2169), (16...",0.99,"[I, G, U, A, L, E, S]",False,None,0
16,0,4032,3024,3,"[(1056, 2151), (3014, 2121), (3019, 2464), (10...",0.84,0,"[(1056, 2151), (3014, 2121), (3019, 2464), (10...",0.84,0,"[(1056, 2151), (1440, 2145), (1445, 2489), (10...",0.99,"[5, 0]",False,None,0
17,0,4032,3024,3,"[(1056, 2151), (3014, 2121), (3019, 2464), (10...",0.84,0,"[(1056, 2151), (3014, 2121), (3019, 2464), (10...",0.84,1,"[(1639, 2142), (1870, 2138), (1875, 2481), (16...",0.99,[%],False,None,0
18,0,4032,3024,3,"[(1056, 2151), (3014, 2121), (3019, 2464), (10...",0.84,0,"[(1056, 2151), (3014, 2121), (3019, 2464), (10...",0.84,2,"[(1985, 2137), (2087, 2135), (2092, 2478), (19...",0.92,[$],True,0,0
19,0,4032,3024,3,"[(1056, 2151), (3014, 2121), (3019, 2464), (10...",0.84,0,"[(1056, 2151), (3014, 2121), (3019, 2464), (10...",0.84,3,"[(2156, 2134), (3014, 2121), (3019, 2465), (21...",0.71,"[1, 0, 7, 2]",False,None,0
20,0,4032,3024,4,"[(533, 2327), (639, 2338), (634, 2388), (528, ...",0.99,0,"[(533, 2327), (639, 2338), (634, 2388), (528, ...",0.99,0,"[(533, 2327), (639, 2338), (634, 2388), (528, ...",0.99,"[P, A, R, A]",False,None,0
21,0,4032,3024,5,"[(317, 2417), (493, 2299), (540, 2368), (364, ...",0.99,0,"[(317, 2417), (493, 2299), (540, 2368), (364, ...",0.99,0,"[(317, 2417), (493, 2299), (540, 2368), (364, ...",0.99,"[A, C, C, I, O, N, E, S]",False,None,0
22,0,4032,3024,6,"[(1528, 2439), (1808, 2437), (1808, 2475), (15...",0.92,0,"[(1528, 2439), (1808, 2437), (1808, 2475), (15...",0.92,0,"[(1528, 2439), (1808, 2437), (1808, 2475), (15...",0.92,"[D, E, S, C, U, E, N, T, O]",False,None,0
23,0,4032,3024,7,"[(1203, 2513), (1684, 2502), (1685, 2548), (12...",0.97,0,"[(1203, 2513), (1684, 2502), (1685, 2548), (12...",0.97,0,"[(1203, 2513), (1266, 2512), (1267, 2558), (12...",0.99,"[E, N]",False,None,0
24,0,4032,3024,7,"[(1203, 2513), (1684, 2502), (1685, 2548), (12...",0.97,0,"[(1203, 2513), (1684, 2502), (1685, 2548), (12...",0.97,1,"[(1287, 2511), (1350, 2510), (1351, 2556), (12...",0.99,"[L, A]",False,None,0
25,0,4032,3024,7,"[(1203, 2513), (1684, 2502), (1685, 2548), (12...",0.97,0,"[(1203, 2513), (1684, 2502), (1685, 2548), (12...",0.97,2,"[(1369, 2509), (1468, 2507), (1469, 2553), (13...",0.93,"[2, D, A]",False,None,0
26,0,4032,3024,7,"[(1203, 2513), (1684, 2502), (1685, 2548), (12...",0.97,0,"[(1203, 2513), (1684, 2502), (1685, 2548), (12...",0.97,3,"[(1485, 2507), (1684, 2502), (1685, 2547), (14...",0.99,"[U, N, I, D, A, D]",False,None,0
27,0,4032,3024,8,"[(2323, 2516), (2525, 2509), (2526, 2540), (23...",0.92,0,"[(2323, 2516), (2525, 2509), (2526, 2540), (23...",0.92,0,"[(2323, 2517), (2408, 2514), (2409, 2544), (23...",0.98,"[P, R, E, C, I, O]",False,None,0
28,0,4032,3024,8,"[(2323, 2516), (2525, 2509), (2526, 2540), (23...",0.92,0,"[(2323, 2516), (2525, 2509), (2526, 2540), (23...",0.92,1,"[(2420, 2513), (2525, 2509), (2526, 2539), (24...",0.86,"[N, O, R, M, A, L]",False,None,0
29,0,4032,3024,9,"[(388, 2475), (677, 2398), (721, 2565), (432, ...",0.99,0,"[(388, 2475), (677, 2398), (721, 2565), (432, ...",0.99,0,"[(388, 2475), (673, 2401), (694, 2482), (409, ...",0.99,"[P, A, G, A, R]",False,None,0
30,0,4032,3024,9,"[(388, 2475), (677, 2398), (721, 2565), (432, ...",0.99,0,"[(388, 2475), (677, 2398), (721, 2565), (432, ...",0.99,1,"[(427, 2556), (699, 2482), (721, 2563), (449, ...",0.99,"[M, E, N, O, S]",False,None,0
31,0,4032,3024,10,"[(1950, 2539), (2065, 2539), (2065, 2640), (19...",0.94,0,"[(1950, 2539), (2065, 2539), (2065, 2640), (19...",0.94,0,"[(1954, 2539), (2061, 2539), (2061, 2585), (19...",0.93,"[M, á, x]",False,None,0
32,0,4032,3024,10,"[(1950, 2539), (2065, 2539), (2065, 2640), (19...",0.94,0,"[(1950, 2539), (2065, 2539), (2065, 2640), (19...",0.94,1,"[(1950, 2600), (2006, 2600), (2006, 2640), (19...",0.99,"[1, 6]",False,None,0
33,0,4032,3024,10,"[(1950, 2539), (2065, 2539), (2065, 2640), (19...",0.94,0,"[(1950, 2539), (2065, 2539), (2065, 2640), (19...",0.94,2,"[(2024, 2600), (2051, 2600), (2051, 2640), (20...",0.94,[u],False,None,0
34,0,4032,3024,10,"[(1950, 2539), (2065, 2539), (2065, 2640), (19...",0.94,0,"[(1950, 2539), (2065, 2539), (2065, 2640), (19...",0.94,3,"[(2055, 2600), (2065, 2600), (2065, 2640), (20...",0.89,[.],False,None,0
35,0,4032,3024,11,"[(2280, 2547), (2546, 2544), (2547, 2647), (22...",0.75,0,"[(2280, 2547), (2546, 2544), (2547, 2647), (22...",0.75,0,"[(2280, 2547), (2303, 2547), (2304, 2650), (22...",0.35,[s],False,None,0
36,0,4032,3024,11,"[(2280, 2547), (2546, 2544), (2547, 2647), (22...",0.75,0,"[(2280, 2547), (2546, 2544), (2547, 2647), (22...",0.75,1,"[(2323, 2547), (2546, 2544), (2547, 2647), (23...",0.89,"[1, 4, 3]",False,None,0
37,0,4032,3024,12,"[(2874, 2532), (2968, 2529), (2971, 2629), (28...",0.08,0,"[(2874, 2532), (2968, 2529), (2971, 2629), (28...",0.08,0,"[(2874, 2532), (2968, 2529), (2971, 2629), (28...",0.08,"[1, 1]",False,None,0
38,0,4032,3024,13,"[(1223, 2605), (1663, 2596), (1664, 2647), (12...",0.99,0,"[(1223, 2605), (1663, 2596), (1664, 2647), (12...",0.99,0,"[(1223, 2605), (1301, 2603), (1302, 2654), (12...",0.99,"[D, e, l]",False,None,0
39,0,4032,3024,13,"[(1223, 2605), (1663, 2596), (1664, 2647), (12...",0.99,0,"[(1223, 2605), (1663, 2596), (1664, 2647), (12...",0.99,1,"[(1320, 2603), (1454, 2600), (1455, 2651), (13...",0.99,"[3, 0, /, 0, 6]",False,None,0
40,0,4032,3024,13,"[(1223, 2605), (1663, 2596), (1664, 2647), (12...",0.99,0,"[(1223, 2605), (1663, 2596), (1664, 2647), (12...",0.99,2,"[(1471, 2600), (1512, 2599), (1513, 2649), (14...",0.99,"[a, l]",False,None,0
41,0,4032,3024,13,"[(1223, 2605), (1663, 2596), (1664, 2647), (12...",0.99,0,"[(1223, 2605), (1663, 2596), (1664, 2647), (12...",0.99,3,"[(1528, 2599), (1663, 2596), (1664, 2646), (15...",0.98,"[0, 6, /, 0, 7]",False,None,0
42,0,4032,3024,14,"[(550, 2625), (570, 2621), (583, 2691), (563, ...",0.07,0,"[(550, 2625), (570, 2621), (583, 2691), (563, ...",0.07,0,"[(550, 2625), (570, 2621), (583, 2691), (563, ...",0.07,[<],False,None,0
43,0,4032,3024,15,"[(2683, 2626), (3013, 2616), (3014, 2652), (26...",0.80,0,"[(2683, 2626), (3013, 2616), (3014, 2652), (26...",0.80,0,"[(2683, 2626), (2890, 2620), (2891, 2656), (26...",0.73,"[7, ., 7, 9, 0, 8, 9, 5]",False,None,0
44,0,4032,3024,15,"[(2683, 2626), (3013, 2616), (3014, 2652), (26...",0.80,0,"[(2683, 2626), (3013, 2616), (3014, 2652), (26...",0.80,1,"[(2905, 2620), (2914, 2620), (2915, 2655), (29...",0.93,"[""]",False,None,0
45,0,4032,3024,15,"[(2683, 2626), (3013, 2616), (3014, 2652), (26...",0.80,0,"[(2683, 2626), (3013, 2616), (3014, 2652), (26...",0.80,2,"[(2925, 2619), (3013, 2616), (3014, 2652), (29...",0.97,"[0, 0, 0]",False,None,0
46,0,4032,3024,16,"[(2200, 2678), (2539, 2668), (2540, 2704), (22...",0.82,0,"[(2200, 2678), (2539, 2668), (2540, 2704), (22...",0.82,0,"[(2200, 2678), (2331, 2674), (2332, 2710), (22...",0.99,"[P, R, E, C, I, O]",False,None,0
47,0,4032,3024,16,"[(2200, 2678), (2539, 2668), (2540, 2704), (22...",0.82,0,"[(2200, 2678), (2539, 2668), (2540, 2704), (22...",0.82,1,"[(2343, 2674), (2390, 2673), (2391, 2708), (23...",0.92,"[X, 1]",False,None,0
48,0,4032,3024,16,"[(2200, 2678), (2539, 2668), (2540, 2704), (22...",0.82,0,"[(2200, 2678), (2539, 2668), (2540, 2704), (22...",0.82,2,"[(2406, 2672), (2421, 2672), (2422, 2707), (24...",0.47,[L],False,None,0
49,0,4032,3024,16,"[(2200, 2678), (2539, 2668), (2540, 2704), (22...",0.82,0,"[(2200, 2678), (2539, 2668), (2540, 2704), (22...",0.82,3,"[(2425, 2672), (2441, 2672), (2442, 2707), (24...",0.16,[:],False,None,0
50,0,4032,3024,16,"[(2200, 2678), (2539, 2668), (2540, 2704), (22...",0.82,0,"[(2200, 2678), (2539, 2668), (2540, 2704), (22...",0.82,4,"[(2453, 2671), (2539, 2669), (2540, 2705), (24...",0.77,"[6, 3, ,, 5, 5]",False,None,0
51,0,4032,3024,17,"[(693, 2687), (754, 2633), (791, 2674), (729, ...",0.81,0,"[(693, 2687), (754, 2633), (791, 2674), (729, ...",0.81,0,"[(693, 2687), (754, 2633), (791, 2674), (729, ...",0.81,"[M, Á, S]",False,None,0
52,0,4032,3024,18,"[(510, 2713), (710, 2696), (716, 2762), (516, ...",0.90,0,"[(510, 2713), (710, 2696), (716, 2762), (516, ...",0.90,0,"[(510, 2713), (710, 2696), (716, 2762), (516, ...",0.90,"[A, H, O, R, R, A, R]",False,None,0
53,0,4032,3024,19,"[(2616, 3195), (2738, 3298), (2657, 3395), (25...",0.60,0,"[(2616, 3195), (2738, 3298), (2657, 3395), (25...",0.60,0,"[(2616, 3195), (2738, 3298), (2657, 3395), (25...",0.60,"[e, c, d]",False,None,0

In [70]:
df = df.drop('20.jpg', level='file')

In [71]:
df.shape

(432, 16)

**Target**

In [73]:
df[df['y']==1]

,,n_page,page_height,page_width,n_block,block_vert,block_confidence,n_paragraph,paragraph_vert,paragraph_confidence,n_word,word_vert,word_confidence,text,symbol_search_pos,n_symbol_search_find,y
file,index,,,,,,,,,,,,,,,,
1.jpg,22,0,719,1280,5,"[(433, 437), (752, 423), (756, 526), (437, 540)]",0.98,0,"[(433, 437), (752, 423), (756, 526), (437, 540)]",0.98,1,"[(505, 434), (752, 424), (756, 526), (509, 537)]",0.98,"[8, 7, ., 5, 0]",False,None,1
2.jpg,19,0,581,1032,4,"[(411, 286), (638, 260), (646, 338), (420, 363)]",0.98,0,"[(411, 286), (638, 260), (646, 338), (420, 363)]",0.98,1,"[(463, 280), (638, 260), (647, 338), (472, 357)]",0.98,"[8, 7, ., 5, 0]",False,None,1
3.jpg,10,0,581,1032,1,"[(259, 273), (534, 271), (535, 353), (260, 355)]",0.49,0,"[(259, 273), (534, 271), (535, 353), (260, 355)]",0.49,2,"[(399, 272), (510, 271), (511, 353), (400, 354)]",0.70,"[1, 5, 2]",False,None,1
4.jpg,7,0,581,1032,2,"[(449, 248), (587, 244), (589, 319), (451, 323)]",0.99,0,"[(449, 248), (587, 244), (589, 319), (451, 323)]",0.99,0,"[(449, 248), (587, 244), (589, 319), (451, 323)]",0.99,"[1, 2, 2]",False,None,1
5.jpg,4,0,719,1280,2,"[(743, 318), (858, 296), (868, 348), (753, 370)]",0.79,0,"[(743, 318), (858, 296), (868, 348), (753, 370)]",0.79,0,"[(743, 318), (832, 301), (842, 353), (753, 370)]",0.99,"[1, 2, 2]",False,None,1
6.jpg,8,0,581,1032,2,"[(479, 145), (704, 143), (705, 198), (480, 200)]",0.52,0,"[(479, 145), (704, 143), (705, 198), (480, 200)]",0.52,0,"[(479, 145), (548, 144), (549, 199), (480, 200)]",0.99,"[8, 7]",False,None,1
7.jpg,9,0,581,1032,1,"[(423, 152), (569, 144), (573, 224), (427, 232)]",0.94,0,"[(423, 152), (569, 144), (573, 224), (427, 232)]",0.94,1,"[(470, 150), (569, 145), (573, 223), (474, 229)]",0.95,"[8, 7]",False,None,1
8.jpg,9,0,960,1280,1,"[(509, 472), (654, 474), (653, 581), (508, 579)]",0.99,0,"[(509, 472), (654, 474), (653, 581), (508, 579)]",0.99,1,"[(543, 472), (654, 473), (653, 580), (542, 579)]",0.99,"[8, 7]",False,None,1
9.jpg,9,0,581,1032,1,"[(388, 216), (535, 236), (523, 323), (376, 303)]",0.94,0,"[(388, 216), (535, 236), (523, 323), (376, 303)]",0.94,1,"[(424, 221), (535, 236), (523, 323), (412, 308)]",0.96,"[1, 5, 2]",False,None,1
10.jpg,10,0,719,1280,1,"[(677, 332), (814, 343), (807, 419), (671, 408)]",0.91,0,"[(677, 332), (814, 343), (807, 419), (671, 408)]",0.91,1,"[(707, 334), (814, 343), (807, 418), (701, 410)]",0.98,"[1, 5, 2]",False,None,1
11.jpg,20,0,581,1032,4,"[(382, 274), (622, 245), (633, 330), (392, 359)]",0.99,0,"[(382, 274), (622, 245), (633, 330), (392, 359)]",0.99,1,"[(437, 267), (623, 244), (633, 330), (447, 352)]",0.99,"[8, 7, ., 5, 0]",False,None,1
12.jpg,19,0,581,1032,4,"[(401, 271), (619, 255), (625, 330), (407, 346)]",0.97,0,"[(401, 271), (619, 255), (625, 330), (407, 346)]",0.97,1,"[(451, 267), (620, 255), (625, 329), (457, 342)]",0.97,"[8, 7, ., 5, 0]",False,None,1
13.jpg,9,0,581,1032,1,"[(376, 243), (759, 248), (758, 320), (375, 315)]",0.46,0,"[(376, 243), (759, 248), (758, 320), (375, 315)]",0.46,1,"[(403, 244), (500, 245), (499, 316), (402, 315)]",0.97,"[1, 5, 2]",False,None,1
14.jpg,8,0,581,1032,1,"[(454, 197), (547, 198), (546, 273), (453, 272)]",0.99,0,"[(454, 197), (547, 198), (546, 273), (453, 272)]",0.99,0,"[(454, 197), (547, 198), (546, 273), (453, 272)]",0.99,"[8, 7]",False,None,1
15.jpg,6,0,581,1032,1,"[(450, 250), (635, 247), (636, 309), (451, 312)]",0.69,0,"[(450, 250), (635, 247), (636, 309), (451, 312)]",0.69,1,"[(489, 249), (594, 247), (595, 309), (490, 311)]",0.91,"[1, 2, 2]",False,None,1
16.jpg,8,0,581,1032,1,"[(272, 203), (568, 200), (569, 276), (273, 279)]",0.56,0,"[(272, 203), (568, 200), (569, 276), (273, 279)]",0.56,1,"[(408, 202), (526, 201), (527, 277), (409, 278)]",0.83,"[1, 2, 2]",False,None,1
17.jpg,12,0,4032,3024,3,"[(953, 2028), (1653, 2017), (1660, 2433), (960...",0.99,0,"[(953, 2028), (1653, 2017), (1660, 2433), (960...",0.99,0,"[(953, 2028), (1653, 2017), (1660, 2433), (960...",0.99,"[1, 4, 3]",False,None,1
18.jpg,10,0,4032,3024,2,"[(1024, 1856), (2173, 1880), (2162, 2391), (10...",0.99,0,"[(1024, 1856), (2173, 1880), (2162, 2391), (10...",0.99,0,"[(1024, 1856), (2173, 1880), (2162, 2391), (10...",0.99,"[1, 1, 4]",False,None,1

In [74]:
df.to_csv('../data/preprocessed/data.csv')